# Generated by Django 5.1.4 on 2026-04-16 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gancdelivery',
            options={'verbose_name': 'DELIVERY', 'verbose_name_plural': 'DELIVERY'},
        ),
        migrations.AlterModelOptions(
            name='gancenrollment',
            options={'verbose_name': 'ENROLLMENT', 'verbose_name_plural': 'ENROLLMENT'},
        ),
        migrations.AlterModelOptions(
            name='gancfirstsession',
            options={'verbose_name': 'ANC-FIRST-SESSION', 'verbose_name_plural': 'ANC-FIRST-SESSION'},
        ),
        migrations.AlterModelOptions(
            name='gancfouthsession',
            options={'verbose_name': 'ANC-FOURTH-SESSION', 'verbose_name_plural': 'ANC-FOURTH-SESSION'},
        ),
        migrations.AlterModelOptions(
            name='gancohort',
            options={'verbose_name': 'COHORT', 'verbose_name_plural': 'COHORT'},
        ),
        migrations.AlterModelOptions(
            name='gancsecondsession',
            options={'verbose_name': 'ANC-SECOND-SESSION', 'verbose_name_plural': 'ANC-SECOND-SESSION'},
        ),
        migrations.AlterModelOptions(
            name='gancthirdsession',
            options={'verbose_name': 'ANC-THIRD-SESSION', 'verbose_name_plural': 'ANC-THIRD-SESSION'},
        ),
        migrations.AlterModelOptions(
            name='grouppncfirstsession',
            options={'verbose_name': 'PNC-FIRST-SESSION', 'verbose_name_plural': 'PNC-FIRST-SESSION'},
        ),
        migrations.AlterModelOptions(
            name='grouppncsecondsession',
            options={'verbose_name': 'PNC-SECOND-SESSION', 'verbose_name_plural': 'PNC-SECOND-SESSION'},
        ),
        migrations.RemoveField(
            model_name='gancohort',
            name='cohortcreatedby',
        ),
        migrations.AddField(
            model_name='gancohort',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='gancohort',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gancgpnc_created_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gancohort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gancohort',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gancgpnc_updated_cohorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
