# Generated by Django 5.1.4 on 2026-04-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0002_alter_gancdelivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancohort',
            name='target_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cohort Target Size'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='contactnumber',
            field=models.CharField(max_length=255, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='edd',
            field=models.DateField(verbose_name='Expected Date of Delivery'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='enrollmentid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Register Number'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='fathername',
            field=models.CharField(max_length=255, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='gafirstanc',
            field=models.PositiveIntegerField(verbose_name='Gestational Age - ANC'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
