# Generated by Django 5.1.4 on 2026-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0003_gancohort_target_size_alter_gancenrollment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancenrollment',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age (Year)'),
        ),
        migrations.AddField(
            model_name='gancenrollment',
            name='education_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education Level'),
        ),
        migrations.AddField(
            model_name='gancenrollment',
            name='gravida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gravida'),
        ),
        migrations.AddField(
            model_name='gancenrollment',
            name='transfer_in',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Transfer In'),
        ),
        migrations.AlterField(
            model_name='gancohort',
            name='cohortchecklist',
            field=models.CharField(default='G-ANC/PNC Logbook V1', max_length=255, verbose_name='Cohort Checklist'),
        ),
        migrations.AlterField(
            model_name='gancohort',
            name='cohortname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Cohort Name'),
        ),
        migrations.AlterField(
            model_name='gancohort',
            name='cohortnumber',
            field=models.PositiveIntegerField(default=1, verbose_name='Cohort Number'),
        ),
        migrations.AlterField(
            model_name='gancohort',
            name='cohortstatus',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20, verbose_name='Cohort Status'),
        ),
    ]
