# Generated by Django 5.1.4 on 2026-04-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0004_gancenrollment_age_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancenrollment',
            name='contactnumber',
            field=models.CharField(max_length=255, verbose_name='Contact Number'),
        ),
    ]
