# Generated by Django 5.1.4 on 2026-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0005_alter_gancenrollment_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancfirstsession',
            name='acalcium',
            field=models.BooleanField(verbose_name='absorbed calcium in the last month(Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='anemia',
            field=models.BooleanField(verbose_name='Anemia (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='bp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='clabexm',
            field=models.BooleanField(verbose_name='Completing Laboratory Exam (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='coughmorethantwoweeks',
            field=models.BooleanField(verbose_name='cough for more than two weeks(Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger signs during pregnancy (Y/N) '),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dhypertension',
            field=models.BooleanField(verbose_name='Diagnosed with hypertension (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dmam',
            field=models.BooleanField(verbose_name='Diagnosed with MAM (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dsam',
            field=models.BooleanField(verbose_name='Diagnosed with SAM (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='hemoglobin',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Hemoglobin'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='ironfolate',
            field=models.BooleanField(verbose_name='Iron Folate/routine Dose(Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='ironfolatepluswomen',
            field=models.BooleanField(verbose_name='Iron folate (30+) for anemic woman(Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='muac',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='MUAC'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='pcalcium',
            field=models.BooleanField(verbose_name='Prescribe-Calcium(Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='presentga',
            field=models.PositiveIntegerField(verbose_name='Present_GA'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rcough',
            field=models.BooleanField(verbose_name='Referred cough for more than two week to DOTS Room'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rhypertensiontoMD',
            field=models.BooleanField(verbose_name='Referred  hypertension to MD (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rmam',
            field=models.BooleanField(verbose_name='Refer MAM to Nutrition Counsellor (Y/N))'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rpositivepuriatomd',
            field=models.BooleanField(verbose_name='Referred  Positive Protin Uria to MD (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rsam',
            field=models.BooleanField(verbose_name='Refer SAM to higher level (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='sessionround',
            field=models.CharField(choices=[('FIRST-SESSION', 'FIRST-SESSION')], default='FIRST-SESSION', max_length=255, verbose_name='Session-Round'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='sessiontype',
            field=models.CharField(choices=[('GROUP-ANC', 'GROUP-ANC')], default='GROUP-ANC', max_length=225, verbose_name='Session-Type'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='ttvaccine',
            field=models.BooleanField(verbose_name='TT vaccine (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='typeofdangersign',
            field=models.CharField(max_length=255, verbose_name='Type of Danger sign'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+,++,+++)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight'),
        ),
    ]
