# Generated by Django 5.1.4 on 2026-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0006_alter_gancfirstsession_acalcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancenrollment',
            name='numerof_ancvisits',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Individual-ANC-Visits'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='gafirstanc',
            field=models.PositiveIntegerField(verbose_name='G-Age'),
        ),
    ]
