# Generated by Django 5.1.4 on 2026-04-19 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0007_gancenrollment_numerof_ancvisits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancenrollment',
            name='gafirstanc',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(24)], verbose_name='G-Age'),
        ),
    ]
