# Generated by Django 5.1.4 on 2026-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0009_alter_gancsecondsession_acalcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancsecondsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger signs during pregnancy (Y/N)'),
        ),
    ]
