# Generated by Django 5.1.4 on 2026-07-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0011_alter_gancthirdsession_acalcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancfouthsession',
            name='acalcium',
            field=models.BooleanField(verbose_name='Absorbed Calcium in the Last Month (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='anemia',
            field=models.BooleanField(verbose_name='Anemia (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='antedepressiondiagnosed',
            field=models.BooleanField(verbose_name='Antenatal Depression Diagnosed (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='antedepressionscreening',
            field=models.BooleanField(verbose_name='Antenatal Depression Screening (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='birthplanningcounseling',
            field=models.BooleanField(verbose_name='Birth Planning Counseling (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='bp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='coughmorethantwoweeks',
            field=models.BooleanField(verbose_name='Cough for More Than Two Weeks (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger Signs During Pregnancy (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dhypertension',
            field=models.BooleanField(verbose_name='Diagnosed with hypertension (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dmam',
            field=models.BooleanField(verbose_name='Diagnosed with MAM (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dsam',
            field=models.BooleanField(verbose_name='Diagnosed with SAM (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='ironfolate',
            field=models.BooleanField(verbose_name='Iron Folate/Routine Dose (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='ironfolatepluswomen',
            field=models.BooleanField(verbose_name='Iron Folate (30+) for Anemic Woman (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='muac',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='MUAC'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='pcalcium',
            field=models.BooleanField(verbose_name='Prescribe Calcium (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='presentga',
            field=models.PositiveIntegerField(verbose_name='Present_GA'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rcough',
            field=models.BooleanField(verbose_name='Referred Cough to DOTS Room (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rhypertensiontoMD',
            field=models.BooleanField(verbose_name='Referred hypertension to MD (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rmam',
            field=models.BooleanField(verbose_name='Refer MAM to Nutrition Counsellor (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rpositivepuriatomd',
            field=models.BooleanField(verbose_name='Referred Positive Protein Uria to MD (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rpsychosocialcounselor',
            field=models.BooleanField(verbose_name='Refer to the Psychosocial Counselor (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rsam',
            field=models.BooleanField(verbose_name='Refer SAM to Higher Level (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='sessionround',
            field=models.CharField(choices=[('FOURTH-SESSION', 'FOURTH-SESSION')], default='FOURTH-SESSION', max_length=255, verbose_name='Session-Round'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='sessiontype',
            field=models.CharField(choices=[('GROUP-ANC', 'GROUP-ANC')], default='GROUP-ANC', max_length=225, verbose_name='Session-Type'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='ttvaccine',
            field=models.BooleanField(verbose_name='TT Vaccine (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='typeofdangersign',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Danger Sign'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine Exam / Protein Uria (NO/+, ++, +++)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight'),
        ),
    ]
