# Generated by Django 5.1.4 on 2026-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0012_alter_gancfouthsession_acalcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancfirstsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('dropout', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent/Dropout)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent/Dropout)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('dropout', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent/Dropout)'),
        ),
        migrations.AlterField(
            model_name='grouppncfirstsession',
            name='attendance',
            field=models.CharField(choices=[('group', 'Group'), ('individual', 'Individual'), ('Dropout', 'Dropout'), ('no', 'No')], max_length=20, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='grouppncsecondsession',
            name='attendance',
            field=models.CharField(choices=[('group', 'Group'), ('individual', 'Individual'), ('Dropout', 'Dropout'), ('no', 'No')], max_length=20, verbose_name='Attendance'),
        ),
    ]
