# Generated by Django 5.1.4 on 2026-08-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0013_alter_gancfirstsession_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancfirstsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check (Y/N)'),
        ),
        migrations.AddField(
            model_name='gancfouthsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check (Y/N)'),
        ),
        migrations.AddField(
            model_name='gancsecondsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check (Y/N)'),
        ),
        migrations.AddField(
            model_name='gancthirdsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check (Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+,++,+++)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine Exam / Protein Uria (NO/+, +, ++, +++)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+, +, ++, +++)'),
        ),
    ]
