# Generated by Django 5.1.4 on 2026-08-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0014_gancfirstsession_urinexamcheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancfirstsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent/Dropout)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+,++,+++)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance (Group/Individual/Absent/Dropout)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+, +, ++, +++)'),
        ),
    ]
