# Generated by Django 5.1.4 on 2026-09-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0015_alter_gancfirstsession_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Delivery complication',
                'verbose_name_plural': 'Delivery complications',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='gancdelivery',
            name='complications',
            field=models.ManyToManyField(blank=True, help_text='Select one or more complications. Select No Complication alone when none occurred.', related_name='deliveries', to='gancgpnc.deliverycomplication', verbose_name='Complications during labor and delivery'),
        ),
    ]
