# Generated by Django 5.1.4 on 2026-09-21 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0016_delivery_complication_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancenrollment',
            name='gafirstanc',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(24)], verbose_name='Gestational Age (weeks) at first ANC'),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks/Comments'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='acalcium',
            field=models.BooleanField(verbose_name='Absorbed calcium in the last month'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='anemia',
            field=models.BooleanField(verbose_name='Anemia'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='clabexm',
            field=models.BooleanField(verbose_name='Completing Laboratory Exam'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='coughmorethantwoweeks',
            field=models.BooleanField(verbose_name='cough for more than two weeks'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger signs during pregnancy'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dhypertension',
            field=models.BooleanField(verbose_name='Diagnosed with hypertension'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dmam',
            field=models.BooleanField(verbose_name='Diagnosed with MAM'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='dsam',
            field=models.BooleanField(verbose_name='Diagnosed with SAM'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='ironfolate',
            field=models.BooleanField(verbose_name='Iron Folate (routine Dose)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='ironfolatepluswomen',
            field=models.BooleanField(verbose_name='Iron folate (30+) for anemic woman'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='muac',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='MUAC(cm)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='pcalcium',
            field=models.BooleanField(verbose_name='Prescribe Calcium'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='presentga',
            field=models.PositiveIntegerField(verbose_name='Present_Gestational Age (Weeks)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rhypertensiontoMD',
            field=models.BooleanField(verbose_name='Referred  hypertension to MD'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rmam',
            field=models.BooleanField(verbose_name='Refer MAM to Nutrition Counsellor'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rpositivepuriatomd',
            field=models.BooleanField(verbose_name='Referred  Positive Protin Uria to MD'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='rsam',
            field=models.BooleanField(verbose_name='Refer SAM to higher level'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='ttvaccine',
            field=models.BooleanField(verbose_name='TT vaccine'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('NO', 'NO'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+,++,+++)'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check'),
        ),
        migrations.AlterField(
            model_name='gancfirstsession',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight(kg)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='acalcium',
            field=models.BooleanField(verbose_name='Absorbed Calcium in the Last Month'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='anemia',
            field=models.BooleanField(verbose_name='Anemia'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='antedepressiondiagnosed',
            field=models.BooleanField(verbose_name='Antenatal Depression Diagnosed'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='antedepressionscreening',
            field=models.BooleanField(verbose_name='Antenatal Depression Screening'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='birthplanningcounseling',
            field=models.BooleanField(verbose_name='Birth Planning Counseling'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='coughmorethantwoweeks',
            field=models.BooleanField(verbose_name='Cough for More Than Two Weeks'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger Signs During Pregnancy'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dhypertension',
            field=models.BooleanField(verbose_name='Diagnosed with hypertension'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dmam',
            field=models.BooleanField(verbose_name='Diagnosed with MAM'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='dsam',
            field=models.BooleanField(verbose_name='Diagnosed with SAM'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='ironfolate',
            field=models.BooleanField(verbose_name='Iron Folate (Routine Dose)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='ironfolatepluswomen',
            field=models.BooleanField(verbose_name='Iron Folate (30+) for Anemic Woman'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='muac',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='MUAC(cm)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='pcalcium',
            field=models.BooleanField(verbose_name='Prescribe Calcium'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='presentga',
            field=models.PositiveIntegerField(verbose_name='Present Gestational Age (weeks)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rcough',
            field=models.BooleanField(verbose_name='Referred Cough to DOTS Room'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rhypertensiontoMD',
            field=models.BooleanField(verbose_name='Referred hypertension to MD'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rmam',
            field=models.BooleanField(verbose_name='Refer MAM to Nutrition Counsellor'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rpositivepuriatomd',
            field=models.BooleanField(verbose_name='Referred Positive Protein Uria to MD'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rpsychosocialcounselor',
            field=models.BooleanField(verbose_name='Refer to the Psychosocial Counselor'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='rsam',
            field=models.BooleanField(verbose_name='Refer SAM to Higher Level'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='ttvaccine',
            field=models.BooleanField(verbose_name='TT Vaccine'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('NO', 'NO'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine Exam / Protein Uria (NO/+, +, ++, +++)'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight(kg)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='acalcium',
            field=models.BooleanField(verbose_name='Absorbed calcium in the last month(Y/N)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='anemia',
            field=models.BooleanField(verbose_name='Anemia'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='coughmorethantwoweeks',
            field=models.BooleanField(verbose_name='Cough for more than two weeks'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger signs during pregnancy'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='dhypertension',
            field=models.BooleanField(verbose_name='Diagnosed with hypertension'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='dmam',
            field=models.BooleanField(verbose_name='Diagnosed with MAM'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='dsam',
            field=models.BooleanField(verbose_name='Diagnosed with SAM'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='ironfolate',
            field=models.BooleanField(verbose_name='Iron Folate (routine Dose)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='ironfolatepluswomen',
            field=models.BooleanField(verbose_name='Iron folate (30+) for anemic woman'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='mebendazole',
            field=models.BooleanField(verbose_name='Mebendazole'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='muac',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='MUAC(cm)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='pcalcium',
            field=models.BooleanField(verbose_name='Prescribe-Calcium'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='presentga',
            field=models.PositiveIntegerField(verbose_name='Present_Gestational Age (weeks)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='rhypertensiontoMD',
            field=models.BooleanField(verbose_name='Referred  hypertension to MD'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='rmam',
            field=models.BooleanField(verbose_name='Refer MAM to Nutrition Counsellor'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='rpositivepuriatomd',
            field=models.BooleanField(verbose_name='Referred  Positive Protin Uria to MD'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='rsam',
            field=models.BooleanField(verbose_name='Refer SAM to higher level'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='ttvaccine',
            field=models.BooleanField(verbose_name='TT vaccine'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('NO', 'NO'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+,++,+++)'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='acalcium',
            field=models.BooleanField(verbose_name='Absorbed calcium in the last month'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='anemia',
            field=models.BooleanField(verbose_name='Anemia'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='antedepressiondiagnosed',
            field=models.BooleanField(verbose_name='Antenatal Depression Diagnosed'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='antedepressionscreening',
            field=models.BooleanField(verbose_name='Antenatal Depression Screening'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='birthplanningcounseling',
            field=models.BooleanField(verbose_name='Birth Planning Counseling'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='coughmorethantwoweeks',
            field=models.BooleanField(verbose_name='Cough for more than two weeks'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='dangersign',
            field=models.BooleanField(verbose_name='Danger signs during pregnancy'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='dhypertension',
            field=models.BooleanField(verbose_name='Diagnosed with hypertension'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='dmam',
            field=models.BooleanField(verbose_name='Diagnosed with MAM'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='dsam',
            field=models.BooleanField(verbose_name='Diagnosed with SAM'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='ironfolate',
            field=models.BooleanField(verbose_name='Iron Folate (routine Dose)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='ironfolatepluswomen',
            field=models.BooleanField(verbose_name='Iron folate (30+) for anemic woman'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='muac',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='MUAC(cm)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='pcalcium',
            field=models.BooleanField(verbose_name='Prescribe-Calcium'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='presentga',
            field=models.PositiveIntegerField(verbose_name='Present Gestational Age (weeks)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='rhypertensiontoMD',
            field=models.BooleanField(verbose_name='Referred  hypertension to MD'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='rmam',
            field=models.BooleanField(verbose_name='Refer MAM to Nutrition Counsellor'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='rpositivepuriatomd',
            field=models.BooleanField(verbose_name='Referred  Positive Protin Uria to MD'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='rpsychosocialcounselor',
            field=models.BooleanField(verbose_name='Refer to the psychosocial counselor'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='rsam',
            field=models.BooleanField(verbose_name='Refer SAM to higher level'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='ttvaccine',
            field=models.BooleanField(verbose_name='TT vaccine'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='urinexam',
            field=models.CharField(choices=[('NO/+', 'NO/+'), ('NO', 'NO'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NO/+', max_length=255, verbose_name='Urine exam/Protein Uria (NO/+, +, ++, +++)'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='urinexamcheck',
            field=models.BooleanField(blank=True, null=True, verbose_name='Urine Exam Check'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Weight(kg)'),
        ),
    ]
