# Generated by Django 5.1.4 on 2026-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gancgpnc', '0017_alter_gancenrollment_gafirstanc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gancfirstsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='gancfouthsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='gancsecondsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='gancthirdsession',
            name='attendance',
            field=models.CharField(choices=[('GROUP', 'GROUP'), ('INDIVIDUAL', 'INDIVIDUAL'), ('DROPOUT', 'DROPOUT'), ('ABSENT', 'ABSENT')], default='GROUP', max_length=255, verbose_name='Attendance'),
        ),
    ]
