# Generated by Django 5.1.1 on 2024-09-19 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessmenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Implementor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=10)),
                ('districtfk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiva.district')),
                ('facilitytypefk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiva.facilitytype')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='provincefk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiva.province'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
                ('areafk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.area')),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
                ('sectionfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.section')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shorname', models.TextField(blank=True)),
                ('scorefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.score')),
                ('standardfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.standards')),
            ],
        ),
    ]
