# Generated by Django 5.1.1 on 2024-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='createdby',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
