# Generated by Django 5.1.1 on 2024-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0002_criteria_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='standards',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
