# Generated by Django 5.1.1 on 2024-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0003_alter_area_name_alter_criteria_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='standards',
            name='name',
            field=models.TextField(),
        ),
    ]
