# Generated by Django 5.1.1 on 2024-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0004_alter_criteria_name_alter_score_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='namedari',
            field=models.TextField(blank=True),
        ),
    ]
