# Generated by Django 5.1.1 on 2024-11-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0005_criteria_namedari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.RenameField(
            model_name='assessmenttype',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.RenameField(
            model_name='criteria',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.RenameField(
            model_name='facilitytype',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.RenameField(
            model_name='implementor',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.RenameField(
            model_name='standards',
            old_name='shorname',
            new_name='shortname',
        ),
    ]
