# Generated by Django 5.1.1 on 2024-11-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0006_rename_shorname_area_shortname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorshipvisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField()),
                ('mentorshipstarttime', models.TimeField()),
                ('mentorshipendtime', models.TimeField()),
                ('mentee', models.CharField()),
                ('mentor', models.CharField()),
                ('topics', models.TextField()),
                ('ls', models.BooleanField()),
                ('pc', models.BooleanField()),
                ('mc', models.BooleanField()),
                ('facilityfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.score')),
            ],
        ),
    ]
