# Generated by Django 5.1.1 on 2024-11-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0007_mentorshipvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='facilityfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor'),
        ),
    ]
