# Generated by Django 5.1.1 on 2024-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0008_alter_mentorshipvisit_facilityfk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='code',
        ),
        migrations.AddField(
            model_name='district',
            name='district',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='districtcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='districtdari',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='districtpashto',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='averagetimetoarive',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='catchment',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='distincefromcity',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='hfcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='namedari',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='namepashto',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='selectionphase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='namedari',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='namepashto',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='province',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='provinceDari',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='provincePashto',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='provincecode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='provinceshortname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
