# Generated by Django 5.1.1 on 2024-11-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0009_remove_facility_code_district_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentdate', models.DateField()),
                ('areafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.area')),
                ('assesorfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor')),
                ('assessmenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessmenttype')),
                ('criteriafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.criteria')),
                ('districtfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.district')),
                ('facilityfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
                ('facilitytypefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facilitytype')),
                ('implementorfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.implementor')),
                ('provincefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.province')),
                ('scorefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.score')),
                ('sectionfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.section')),
                ('standardfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.standards')),
            ],
        ),
    ]
