# Generated by Django 5.1.1 on 2024-11-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0010_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
