# Generated by Django 5.1.1 on 2024-11-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0011_assessment_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='districtfk',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='provincefk',
        ),
    ]
