# Generated by Django 5.1.1 on 2024-11-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0012_remove_assessment_districtfk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='facilitytypefk',
        ),
    ]
