# Generated by Django 5.1.1 on 2024-11-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0013_remove_assessment_facilitytypefk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='assessor',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='gender',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='tazkira',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='dropoutdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='selectiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
