# Generated by Django 5.1.1 on 2024-11-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0014_rename_latitude_facility_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainvenue', models.TextField()),
                ('trainstartdate', models.DateField()),
                ('trainenddate', models.DateField()),
                ('hivastaff', models.CharField()),
                ('hivaclinicalstaff', models.CharField()),
                ('firstname', models.CharField()),
                ('lastname', models.CharField()),
                ('fathername', models.CharField()),
                ('nid', models.CharField()),
                ('gender', models.CharField()),
                ('contactnumber', models.CharField()),
                ('participantemail', models.CharField()),
                ('participantprovinice', models.CharField()),
                ('participantdistrict', models.CharField()),
                ('participanteducation', models.TextField()),
                ('trainingtitle', models.TextField()),
                ('thematicarea', models.CharField()),
                ('participationtype', models.CharField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.province')),
            ],
        ),
    ]
