# Generated by Django 5.1.1 on 2024-11-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0015_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='trainingbatch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='thematicarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.area'),
        ),
        migrations.AlterField(
            model_name='training',
            name='participationtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.participationtype'),
        ),
    ]
