# Generated by Django 5.1.1 on 2024-11-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0017_mentorshiptopics_thematicmentorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiptopics',
            name='thematicfk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.thematicmentorship'),
        ),
    ]
