# Generated by Django 5.1.1 on 2024-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0018_mentorshiptopics_thematicfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiptopics',
            name='shortname',
            field=models.CharField(blank=True, null=True),
        ),
    ]
