# Generated by Django 5.1.1 on 2024-11-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0019_mentorshiptopics_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiptopics',
            name='name',
            field=models.TextField(),
        ),
    ]
