# Generated by Django 5.1.1 on 2024-11-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0020_alter_mentorshiptopics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='topics',
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='menteegender',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='menteename',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='menteeprofession',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='thematicname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.thematicmentorship'),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='topicname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.mentorshiptopics'),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshipvisit',
            name='visitround',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
