# Generated by Django 5.1.1 on 2024-12-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0021_remove_mentorshipvisit_mentee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='ls',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='mc',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='menteegender',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='menteename',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='menteeprofession',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='pc',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='thematicname',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='topicname',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='Mentorshipdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menteename', models.CharField(blank=True, null=True)),
                ('menteeprofession', models.CharField(blank=True, null=True)),
                ('menteegender', models.CharField(blank=True, null=True)),
                ('ls', models.BooleanField()),
                ('pc', models.BooleanField()),
                ('mc', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor')),
                ('mentorshipvist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='hiva.mentorshipvisit')),
                ('thematicname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.thematicmentorship')),
                ('topicname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.mentorshiptopics')),
            ],
        ),
    ]
