# Generated by Django 5.1.1 on 2024-12-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0022_remove_mentorshipvisit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipdetails',
            name='mentorshipvist',
        ),
        migrations.AddField(
            model_name='mentorshipdetails',
            name='mentorshipvistfk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hiva.mentorshipvisit'),
        ),
    ]
