# Generated by Django 5.1.1 on 2024-12-01 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0023_remove_mentorshipdetails_mentorshipvist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='topicname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.mentorshiptopics', verbose_name='shortname'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField()),
                ('lastname', models.DateField()),
                ('tazkiranumber', models.CharField()),
                ('gender', models.CharField()),
                ('status', models.CharField()),
                ('hfname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.position')),
            ],
        ),
    ]
