# Generated by Django 5.1.1 on 2024-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0024_position_alter_mentorshipdetails_topicname_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(),
        ),
    ]
