# Generated by Django 5.1.1 on 2024-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0025_alter_staff_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tazkiranumber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
