# Generated by Django 5.1.1 on 2024-12-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0026_alter_staff_lastname_alter_staff_tazkiranumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipdetails',
            name='menteegender',
        ),
        migrations.RemoveField(
            model_name='mentorshipdetails',
            name='menteeprofession',
        ),
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='menteename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.staff'),
        ),
    ]
