# Generated by Django 5.1.1 on 2024-12-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0027_remove_mentorshipdetails_menteegender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ProjectGoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.projectgoal')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ProjectObjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.projectobjective')),
            ],
        ),
    ]
