# Generated by Django 5.1.1 on 2024-12-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0029_indicatortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datasource', models.TextField()),
                ('baseline', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('achivement', models.CharField()),
                ('remarks', models.CharField(max_length=200)),
                ('indicatoroutput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.projectobjective')),
                ('indicatortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.indicatortype')),
            ],
        ),
    ]
