# Generated by Django 5.1.1 on 2024-12-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0030_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicatormodality',
            field=models.CharField(blank=True, null=True),
        ),
    ]
