# Generated by Django 5.1.1 on 2024-12-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0031_indicator_indicatormodality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participanteducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participantposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainingheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingname', models.TextField()),
                ('trainingvenue', models.TextField()),
                ('trainingstartdate', models.DateField()),
                ('trainingenddate', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainenddate',
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainingtitle',
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainstartdate',
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainvenue',
        ),
        migrations.AlterField(
            model_name='training',
            name='participanteducation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.participanteducation'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainingheader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.trainingheader'),
        ),
    ]
