# Generated by Django 5.1.1 on 2024-12-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0032_participanteducation_participantposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingheader',
            name='expectednumberofparticipant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingheader',
            name='traingfocalpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
