# Generated by Django 5.1.1 on 2024-12-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0033_trainingheader_expectednumberofparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='participantposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.participantposition'),
        ),
    ]
