# Generated by Django 5.1.1 on 2024-12-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0034_training_participantposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='contactnumber',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='participantemail',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingheader',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
