# Generated by Django 5.1.1 on 2024-12-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0035_alter_training_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='hivaclinicalstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor'),
        ),
    ]
