# Generated by Django 5.1.1 on 2024-12-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0036_alter_training_hivaclinicalstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='province',
        ),
        migrations.AddField(
            model_name='training',
            name='Serviceprovider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.implementor'),
        ),
        migrations.AlterField(
            model_name='training',
            name='participantdistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.district'),
        ),
        migrations.AlterField(
            model_name='training',
            name='participantprovinice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.province'),
        ),
    ]
