# Generated by Django 5.1.1 on 2024-12-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0037_remove_training_province_training_serviceprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='currentaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
