# Generated by Django 5.1.1 on 2024-12-12 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0038_training_currentaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qqmdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QqmdomainIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('remarks', models.TextField()),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.qqmdomain')),
            ],
        ),
    ]
