# Generated by Django 5.1.1 on 2024-12-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0039_qqmdomain_qqmdomainindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqmdomainindicator',
            name='auditdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qqmdomainindicator',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.facility'),
        ),
        migrations.AddField(
            model_name='qqmdomainindicator',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='qqmdomainindicator',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
