# Generated by Django 5.1.1 on 2024-12-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0040_qqmdomainindicator_auditdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qqmdomainindicator',
            name='auditdate',
        ),
        migrations.RemoveField(
            model_name='qqmdomainindicator',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='qqmdomainindicator',
            name='score',
        ),
        migrations.CreateModel(
            name='tpm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditdate', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField()),
                ('domainindicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.qqmdomainindicator')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
            ],
        ),
    ]
