# Generated by Django 5.1.1 on 2024-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0041_remove_qqmdomainindicator_auditdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanteducation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantposition',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qqmdomain',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qqmdomainindicator',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpm',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
