# Generated by Django 5.1.1 on 2024-12-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0042_alter_participanteducation_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qiccriterialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiccriteriadate', models.DateField()),
                ('qiccriterianame', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qicdataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiccommdate', models.DateField()),
                ('qictotalquestions', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('qicdatacollector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor')),
                ('qicfacility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
                ('qictoravail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to='hiva.qiccriterialist')),
            ],
        ),
    ]
