# Generated by Django 5.1.1 on 2024-12-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0043_qiccriterialist_qicdataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qicdataset',
            name='qictoravail',
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qichealthshurainvolvedincorractvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qichqiptollavailvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qiclastmonthvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmenteelogbookavialvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmenteelogbookupdatedvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmetwithhealthshuravalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmmavialvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmmdatausevalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmmsignedvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicngoinvolvedvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpeertopeeravailvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpipavailvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpipupdatedvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qictoravailvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qictotalquestions',
            field=models.IntegerField(default=0),
        ),
    ]
