# Generated by Django 5.1.1 on 2024-12-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0044_remove_qicdataset_qictoravail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qicdataset',
            name='qicimplementor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.implementor'),
        ),
    ]
