# Generated by Django 5.1.1 on 2024-12-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0045_qicdataset_qicimplementor'),
    ]

    operations = [
        migrations.AddField(
            model_name='qicdataset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qic-minutes/'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
