# Generated by Django 5.1.1 on 2025-01-27 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0046_qicdataset_image_qicdataset_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qicdataset',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='qic-minutes/'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qichealthshurainvolvedincorractvalue',
            field=models.IntegerField(default=0, verbose_name='14. Has the HF Shura-e-Sihie been involved in the completion of the corrective actions in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qichqiptollavailvalue',
            field=models.IntegerField(default=0, verbose_name='6. Is a copy of the Harmonized Quality Improvement Program (HQIP) tool available and accessible at the HF? '),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qiclastmonthvalue',
            field=models.IntegerField(default=0, verbose_name='2. Was the QI committee’s meeting conducted in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmenteelogbookavialvalue',
            field=models.IntegerField(default=0, verbose_name='11. Is the mentee logbook available in the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmenteelogbookupdatedvalue',
            field=models.IntegerField(default=0, verbose_name='12. Has the mentee logbook been updated with the learning sessions conducted in last month and signed by the mentors of the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmetwithhealthshuravalue',
            field=models.IntegerField(default=0, verbose_name='13. Has the QI committee met the HF Shura-e-Sihie in last month? Please refer to the related meeting minutes'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmmavialvalue',
            field=models.IntegerField(default=0, verbose_name='3. Are the meeting minutes of QI committee’s last month’s meeting available.'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmmdatausevalue',
            field=models.IntegerField(default=0, verbose_name='5. Were data use discussed in the last month QI committee’s meeting? Please refer to the meeting minutes of last month'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmmsignedvalue',
            field=models.IntegerField(default=0, verbose_name='4. Did the participants of the QI committee sign the meeting minutes of last month meeting?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicngoinvolvedvalue',
            field=models.IntegerField(default=0, verbose_name='9. Has the NGO been involved in the corrective actions completed in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpeertopeeravailvalue',
            field=models.IntegerField(default=0, verbose_name='10. Have peer to peer learning sessions been conducted within the health facility during the last month? i.e. learning sessions conducted by QI focal point or QI committee members for the HF staff'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpipavailvalue',
            field=models.IntegerField(default=0, verbose_name='7. Is a Performance Improvement Plan (PIP available at the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpipupdatedvalue',
            field=models.IntegerField(default=0, verbose_name='8. Has the PIP been updated in last month QI committee’s meeting? Write number of completed corrective actions'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qictoravailvalue',
            field=models.IntegerField(default=0, verbose_name='1. Are the Terms of Reference (TOR) of QI focal point and QI committee available at HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Mpdsr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearmpdsr', models.IntegerField()),
                ('monthmpdsr', models.CharField(max_length=200)),
                ('n_mpdsrcommittee', models.IntegerField(default=0, verbose_name='Number HF staff who participated in the MPDSR Committee')),
                ('n_maternaldeathreported', models.IntegerField(default=0, verbose_name='Number of Maternal Death reported')),
                ('n_maternaldeathreviewed', models.IntegerField(default=0, verbose_name='Number of Maternal Death reviewed')),
                ('causeofmaternaldeaths_m', models.CharField(max_length=200, verbose_name='Cause of maternal deaths')),
                ('nastillbirthreportedreported', models.IntegerField(default=0, verbose_name='Number of antepartum Still birth reported')),
                ('nastillbirthreportedreviewed', models.IntegerField(default=0, verbose_name='Number of antepartum Still birth reviewed')),
                ('nistillbirthreported', models.IntegerField(default=0, verbose_name='Number of intrapartum Still birth reported')),
                ('nistillbirthreviewed', models.IntegerField(default=0, verbose_name='Number of intrapartum Still birth reviewed')),
                ('nndeath_afteralivebirth_reported', models.IntegerField(default=0, verbose_name='Number of Neonatal Death (after a live birth) reported')),
                ('nndeath_afteralivebirth_reviewed', models.IntegerField(default=0, verbose_name='Number of neonatal Death (after a live birth) reviewed')),
                ('causeofneonataldeath_n', models.CharField(max_length=200, verbose_name='Cause of neonatal death')),
                ('interventionperformed', models.CharField(max_length=200, verbose_name='Intervention performed')),
                ('recfromMPDSRcommittee', models.IntegerField(default=0, verbose_name='Recommendation from MPDSR committee')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='mpdsr-docs/')),
                ('uploaded_at', models.DateField(auto_now_add=True, null=True)),
                ('facilityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
            ],
        ),
    ]
