# Generated by Django 5.1.1 on 2025-01-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0047_alter_qicdataset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdsr',
            name='facilityname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility Name'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='monthmpdsr',
            field=models.CharField(default='January', max_length=200, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='recfromMPDSRcommittee',
            field=models.CharField(max_length=500, verbose_name='Recommendation from MPDSR committee'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='yearmpdsr',
            field=models.IntegerField(default=2025, verbose_name='Year'),
        ),
    ]
