# Generated by Django 5.1.1 on 2025-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0049_gancenrollment_gancfirstsession_gancohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gancenrollment',
            name='enrollmentid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gancenrollment',
            name='fathername',
            field=models.TextField(),
        ),
    ]
