# Generated by Django 5.1.1 on 2025-03-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0050_gancenrollment_enrollmentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='Status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='implementer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.implementor'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.province'),
        ),
    ]
