# Generated by Django 5.1.1 on 2025-04-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0051_assessor_status_assessor_implementer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabtracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilllabname', models.CharField()),
                ('skilllabstatus', models.CharField()),
                ('skilllabround', models.IntegerField()),
                ('skilllabdate', models.DateField()),
                ('skilllabcheckin', models.TimeField()),
                ('skilllabcheckout', models.TimeField()),
                ('ls', models.BooleanField()),
                ('mc', models.BooleanField()),
                ('mentororg', models.CharField()),
                ('ce_checklist_applied', models.BooleanField()),
                ('hfname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor')),
                ('skilllabmenteename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.staff')),
                ('thematicname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.thematicmentorship')),
                ('topicname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.mentorshiptopics')),
            ],
        ),
    ]
