# Generated by Django 5.1.1 on 2025-04-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0052_skilllabtracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gancsecondsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessiontype', models.TextField()),
                ('sessionround', models.IntegerField()),
                ('sessiondate', models.DateField()),
                ('attendance', models.TextField(verbose_name='Attendance (Group/Individual/No)')),
                ('presentga', models.IntegerField(verbose_name='Present_GA')),
                ('bp', models.TextField()),
                ('dhypertension', models.TextField(verbose_name='Diagnosed with hypertension (Y/N)')),
                ('rhypertensiontoMD', models.TextField(verbose_name='Referred  hypertension to MD (Y/N)')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('anemia', models.TextField(verbose_name='Anemia (Y/N)')),
                ('ironfolate', models.TextField(verbose_name='Iron Folate/routine Dose(Y/N)')),
                ('ironfolatepluswomen', models.TextField(verbose_name='Iron folate (30+) for anemic woman(Y/N)')),
                ('pcalcium', models.TextField(verbose_name='Prescribe-Calcium(Y/N)')),
                ('acalcium', models.TextField(verbose_name='absorbed calcium in the last month(Y/N)')),
                ('mebendazole', models.TextField(verbose_name='Mebendazole (Y/N)')),
                ('muac', models.TextField(verbose_name='MUAC')),
                ('dmam', models.TextField(verbose_name='Diagnosed with MAM (Y/N)')),
                ('rmam', models.TextField(verbose_name='Refer MAM to Nutrition Counsellor (Y/N))')),
                ('dsam', models.TextField(verbose_name='Diagnosed with SAM (Y/N)')),
                ('rsam', models.TextField(verbose_name='Refer SAM to higher level (Y/N)')),
                ('urinexam', models.TextField(verbose_name='Urine exam/Protein Uria (NO/+,++,+++)')),
                ('rpositivepuriatomd', models.TextField(verbose_name='Referred  Positive Protin Uria to MD (Y/N)')),
                ('coughmorethantwoweeks', models.TextField(verbose_name='cough for more than two weeks(Y/N)')),
                ('rcough', models.TextField(verbose_name='Referred cough for more than two week to DOTS Room')),
                ('ttvaccine', models.TextField(verbose_name='TT vaccine (Y/N)')),
                ('dangersign', models.TextField(verbose_name='Danger signs during pregnancy (Y/N) ')),
                ('typeofdangersign', models.TextField(verbose_name='Type of Danger sign')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('registerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.gancenrollment', verbose_name='Register Name')),
            ],
        ),
    ]
