# Generated by Django 5.1.1 on 2025-07-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0054_gancthirdsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='aim',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='ganc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='safesurgery',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
