# Generated by Django 5.1.1 on 2025-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0055_facility_aim_facility_ganc_facility_safesurgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='afiat',
            field=models.BooleanField(blank=True, null=True, verbose_name='AFIAT'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='aim',
            field=models.BooleanField(blank=True, null=True, verbose_name='AIM'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ganc',
            field=models.BooleanField(blank=True, null=True, verbose_name='G-ANC/G-PNC'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='safesurgery',
            field=models.BooleanField(blank=True, null=True, verbose_name='Safe Surgery'),
        ),
    ]
