# Generated by Django 5.1.1 on 2025-07-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0056_facility_afiat_alter_facility_aim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='aimphase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='skilllab',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='districtfk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiva.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facilitytypefk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiva.facilitytype', verbose_name='Facility Type'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Facility Name'),
        ),
    ]
