# Generated by Django 5.1.1 on 2025-08-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0057_facility_aimphase_facility_skilllab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor'),
        ),
    ]
