# Generated by Django 5.1.1 on 2025-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0058_alter_mentorshipdetails_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='hfcode',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
