# Generated by Django 5.1.1 on 2025-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0059_alter_facility_hfcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='hfcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
