# Generated by Django 5.1.1 on 2025-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0061_alter_facility_hfcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='hfcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
