# Generated by Django 5.1.1 on 2025-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0063_alter_facility_hfcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiptopics',
            name='namedari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiptopics',
            name='namepashto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
