# Generated by Django 5.1.1 on 2025-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0064_mentorshiptopics_namedari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiptopics',
            name='nameeng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
