# Generated by Django 5.1.1 on 2025-11-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0065_mentorshiptopics_nameeng'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='phase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
