# Generated by Django 5.1.1 on 2025-11-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0066_province_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='continuetophase2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='phaseonecloseout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
