# Generated by Django 5.1.1 on 2025-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0067_assessor_continuetophase2_assessor_phaseonecloseout'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
