# Generated by Django 5.1.1 on 2025-12-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0068_assessor_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='aimpee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamsimonth', models.CharField()),
                ('shamsiyear', models.CharField()),
                ('period', models.CharField()),
                ('bl_progress', models.CharField()),
                ('gre_month', models.CharField()),
                ('gre_year', models.CharField()),
                ('afiat_flag', models.BooleanField()),
                ('womenseenANC', models.BigIntegerField(verbose_name='Pregnant women seen in ANC')),
                ('womenseen_BPANC', models.BigIntegerField(verbose_name='Number of ANC women who had their blood pressure taken')),
                ('womenseenPRE_E_Diagnosed', models.BigIntegerField(verbose_name='Number of ANC women with Pre-E diagnosed (BP>140/90, 2+ proteinuria)')),
                ('aimfacilityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility Name')),
            ],
        ),
        migrations.DeleteModel(
            name='SkillLabtracker',
        ),
    ]
