# Generated by Django 5.1.1 on 2025-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0069_aimpee_delete_skilllabtracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimpee',
            options={'verbose_name': 'AIM-PEE', 'verbose_name_plural': 'AIM-PEE'},
        ),
        migrations.AddField(
            model_name='aimpee',
            name='admitted_patients',
            field=models.BigIntegerField(null=True, verbose_name='Number of Patients with Pre-E diagnosed in ANC clinic who required admision (Admitted patients)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='allbirths',
            field=models.BigIntegerField(null=True, verbose_name='Number of ALL births (log book) including births from PEE patients referred in'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='c_section',
            field=models.BigIntegerField(null=True, verbose_name='Number of birth- by C-sections'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='complications',
            field=models.BigIntegerField(null=True, verbose_name='Complications from Eclampsia and Severe Pre-Eclampsia (number of cases):'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='eclampsia',
            field=models.BigIntegerField(null=True, verbose_name='Number of Patients with Eclampsia coming from ANC, Labor ward or PNC or referred in'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='gestational_hypertension',
            field=models.BigIntegerField(null=True, verbose_name='Gestational hypertension*BP greater than 140/90 after 20 weeks gestation with no proteinuria that is resolved after 42 days postpartum'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='hypertension',
            field=models.BigIntegerField(null=True, verbose_name='Number of patients with chronic hypertension* with superimposed pre-eclampsia'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='severePre_E',
            field=models.BigIntegerField(null=True, verbose_name='Number of Patients with Severe Pre-E at birth (including referrals in)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='vaginal_del',
            field=models.BigIntegerField(null=True, verbose_name='Number of Births - by Vaginal delivery'),
        ),
    ]
