# Generated by Django 5.1.1 on 2025-12-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0070_alter_aimpee_options_aimpee_admitted_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimpee',
            name='admitted_patients',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='allbirths',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='c_section',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='eclampsia',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='gestational_hypertension',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='severePre_E',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='vaginal_del',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='womenseenANC',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='womenseenPRE_E_Diagnosed',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='womenseen_BPANC',
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_aortic_compression',
            field=models.BigIntegerField(default=0, verbose_name='Aortic compression'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_blynch_ual',
            field=models.BigIntegerField(default=0, verbose_name='B-Lynch suture or uterine artery ligation'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_hysterectomy_other',
            field=models.BigIntegerField(default=0, verbose_name='Postpartum hysterectomy (other causes)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_lac_repair',
            field=models.BigIntegerField(default=0, verbose_name='Repair of severe vaginal or cervical lacerations causing a PPH'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_nasg',
            field=models.BigIntegerField(default=0, verbose_name='Anti-shock garment (NASG)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_pph_hysterectomy',
            field=models.BigIntegerField(default=0, verbose_name='Postpartum hysterectomy for hemorrhage'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_ruptured_uterus_repair',
            field=models.BigIntegerField(default=0, verbose_name='Repair ruptured uterus'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_total',
            field=models.BigIntegerField(default=0, verbose_name='Total number of advanced interventions conducted'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='ai_ubt',
            field=models.BigIntegerField(default=0, verbose_name='UBT (condom catheter)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_eclamptic_coma',
            field=models.BigIntegerField(default=0, verbose_name='Eclamptic coma'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_eclamptic_seizure',
            field=models.BigIntegerField(default=0, verbose_name='Eclamptic seizure'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_hellp',
            field=models.BigIntegerField(default=0, verbose_name='HELLP syndrome'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_iufd',
            field=models.BigIntegerField(default=0, verbose_name='Intrauterine Fetal Death'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_placental_abruption',
            field=models.BigIntegerField(default=0, verbose_name='Placental abruption'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_pres',
            field=models.BigIntegerField(default=0, verbose_name='PRES (Posterior Reversible Encephalopathy Syndrome)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_pulmonary_edema',
            field=models.BigIntegerField(default=0, verbose_name='Pulmonary edema'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_renal_failure',
            field=models.BigIntegerField(default=0, verbose_name='Renal Failure (less than 30 ml/hr for 4 hours despite fluid challenge)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_stroke',
            field=models.BigIntegerField(default=0, verbose_name='Stroke (Cerebral hemorrhage or blood clot in brain)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_thrombocytopenia',
            field=models.BigIntegerField(default=0, verbose_name='Thrombocytopenia (not HELLP)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='comp_total',
            field=models.BigIntegerField(default=0, verbose_name='Total complications due to SPE and Eclampsia'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='maternal_death_spe_e',
            field=models.BigIntegerField(default=0, verbose_name='Maternal death due to SPE or Eclampsia'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_anc_bp_taken',
            field=models.BigIntegerField(default=0, verbose_name='Number of ANC women who had their blood pressure taken'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_anc_pree_admit',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with Pre-E diagnosed in ANC clinic who required admission'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_anc_pree_dx',
            field=models.BigIntegerField(default=0, verbose_name='Number of ANC women with Pre-E diagnosed (BP>140/90, 2+ proteinuria)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_anc_preg_seen',
            field=models.BigIntegerField(default=0, verbose_name='Number of pregnant women seen in ANC'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_chronic_htn_superimposed_pe',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with chronic hypertension with superimposed pre-eclampsia'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_eclampsia_admit_before_delivery',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients admitted to HFs with Eclampsia before delivery'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_eclampsia_at_birth',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with Eclampsia from ANC, Labor, PNC or referred in'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_eclampsia_deliv_12h',
            field=models.BigIntegerField(default=0, verbose_name='Number of Eclampsia patients who delivered within 12 hours of admission'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_gest_htn',
            field=models.BigIntegerField(default=0, verbose_name='Gestational hypertension'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_opd_pree_dx_md',
            field=models.BigIntegerField(default=0, verbose_name='Number of outpatients diagnosed in OPD with Pre-Eclampsia by MD'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_opd_pree_twice_week',
            field=models.BigIntegerField(default=0, verbose_name='Number of outpatients with Pre-Eclampsia who returned to ANC/OPD twice a week'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_opd_pree_weekly_labs',
            field=models.BigIntegerField(default=0, verbose_name='Number of outpatients with Pre-Eclampsia who received weekly laboratory testing'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_severe_pe_e_bp160',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with Severe Pre-Eclampsia or Eclampsia WITH BP > 160 systolic OR 110 diastolic'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_severe_pe_e_bp160_tx1h',
            field=models.BigIntegerField(default=0, verbose_name='Number of Severe Pre-E/E patients (BP >160/110) who received antihypertensive medication within one hour of diagnosis'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_spe_admit_before_delivery',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients admitted to HFs with Severe Pre-Eclampsia (SPE) before delivery'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_spe_at_birth',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with Severe Pre-E at birth (including referrals in)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_spe_deliv_24h',
            field=models.BigIntegerField(default=0, verbose_name='Number of Severe Pre-E patients who delivered within 24 hours of admission'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_spe_e_fu_3d',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with SPE or Eclampsia who had a follow-up visit within 3 days after delivery discharge'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_spe_e_mgso4_1h',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with Severe Pre-E or Eclampsia who received Magnesium Sulfate within one hour of diagnosis'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='num_spe_e_pp_dx',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with SPE or Eclampsia diagnosed during the postpartum period'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='pct_opd_pree_weekly_labs',
            field=models.BigIntegerField(default=0, verbose_name='Percentage of outpatients with Pre-Eclampsia who received weekly laboratory testing'),
        ),
    ]
