# Generated by Django 5.1.1 on 2025-12-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0071_remove_aimpee_admitted_patients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aimpph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamsimonth', models.CharField()),
                ('shamsiyear', models.CharField()),
                ('period', models.CharField()),
                ('bl_progress', models.CharField()),
                ('gre_month', models.CharField()),
                ('gre_year', models.CharField()),
                ('afiat_flag', models.BooleanField()),
                ('total_births', models.BigIntegerField(default=0, verbose_name='Number of ALL births (log book)')),
                ('births_vaginal', models.BigIntegerField(default=0, verbose_name='Number of births - by vaginal delivery')),
                ('births_csection', models.BigIntegerField(default=0, verbose_name='Number of births - by C-sections')),
                ('oxytocin_immediate', models.BigIntegerField(default=0, verbose_name='Number of patients receiving oxytocin immediately after birth')),
                ('antepartum_hemorrhage', models.BigIntegerField(default=0, verbose_name='Number of Antepartum Hemorrhage (Abruption, Placenta Previa)')),
                ('pph_vaginal_501_999', models.BigIntegerField(default=0, verbose_name='Number of Postpartum Hemorrhage (PPH) - after vaginal delivery (501–999 cc)')),
                ('pph_cs_1000_plus', models.BigIntegerField(default=0, verbose_name='Number of Postpartum Hemorrhage (PPH) - after Cesarean delivery (≥1000 cc)')),
                ('pph_referral_in_outside_aim', models.BigIntegerField(default=0, verbose_name='Number of Postpartum Hemorrhage (PPH) referrals in from outside of AIM facilities')),
                ('pph_referral_in_aim', models.BigIntegerField(default=0, verbose_name='Number of Postpartum Hemorrhage (PPH) referrals in from AIM facilities')),
                ('qbl_0_500', models.BigIntegerField(default=0, verbose_name='0–500 ml (Normal blood loss, NO PPH)')),
                ('qbl_501_999', models.BigIntegerField(default=0, verbose_name='501–999 ml')),
                ('qbl_1000_1499', models.BigIntegerField(default=0, verbose_name='1000–1499 ml')),
                ('qbl_1500_1999', models.BigIntegerField(default=0, verbose_name='1500–1999 ml')),
                ('qbl_2000_2499', models.BigIntegerField(default=0, verbose_name='2000–2499 ml')),
                ('qbl_2500_plus', models.BigIntegerField(default=0, verbose_name='> 2500 ml')),
                ('qbl_unknown', models.BigIntegerField(default=0, verbose_name='Unknown (estimated blood loss not recorded)')),
                ('qbl_total', models.BigIntegerField(default=0, verbose_name='QBL total')),
                ('transfers_out_pph', models.BigIntegerField(default=0, verbose_name='Number of patients transferred out from HF for PPH')),
                ('maternal_death_pph_transfer', models.BigIntegerField(default=0, verbose_name='Number of maternal deaths (transfers) due to PPH')),
                ('maternal_death_other_transfer', models.BigIntegerField(default=0, verbose_name='Number of maternal deaths (transfers) due to other causes')),
                ('maternal_death_total_transfer', models.BigIntegerField(default=0, verbose_name='Total number of maternal deaths (transfers) – PPH and other causes')),
                ('cause_uterine_atony', models.BigIntegerField(default=0, verbose_name='Uterine atony')),
                ('cause_severe_lacerations', models.BigIntegerField(default=0, verbose_name='Severe vaginal or cervical lacerations which contributed to the PPH')),
                ('cause_retained_products', models.BigIntegerField(default=0, verbose_name='Retained products of conception (total or partial retention of placenta)')),
                ('cause_dic', models.BigIntegerField(default=0, verbose_name='DIC (coagulopathy)')),
                ('cause_ruptured_uterus', models.BigIntegerField(default=0, verbose_name='Ruptured uterus')),
                ('cause_abruption', models.BigIntegerField(default=0, verbose_name='Abruption placenta')),
                ('cause_placenta_previa', models.BigIntegerField(default=0, verbose_name='Placenta previa')),
                ('cause_placenta_accreta', models.BigIntegerField(default=0, verbose_name='Placenta accreta')),
                ('cause_other', models.BigIntegerField(default=0, verbose_name='Other causes of PPH')),
                ('cause_unknown', models.BigIntegerField(default=0, verbose_name='Unknown cause of PPH')),
                ('causes_total', models.BigIntegerField(default=0, verbose_name='TOTAL causes of PPH (may be more than 100%)')),
                ('ai_uterine_compression', models.BigIntegerField(default=0, verbose_name='Uterine compression')),
                ('ai_manual_placenta', models.BigIntegerField(default=0, verbose_name='Manual removal of placenta')),
                ('ai_aortic_compression', models.BigIntegerField(default=0, verbose_name='Aortic compression')),
                ('ai_ubt', models.BigIntegerField(default=0, verbose_name='UBT (condom catheter)')),
                ('ai_lac_repair', models.BigIntegerField(default=0, verbose_name='Repair of severe vaginal or cervical lacerations causing a PPH')),
                ('ai_blynch_ual', models.BigIntegerField(default=0, verbose_name='B-Lynch suture or uterine artery ligation')),
                ('ai_nasg', models.BigIntegerField(default=0, verbose_name='Anti-shock garment (NASG)')),
                ('ai_ruptured_uterus_repair', models.BigIntegerField(default=0, verbose_name='Repair ruptured uterus')),
                ('ai_pph_hysterectomy', models.BigIntegerField(default=0, verbose_name='Postpartum hysterectomy for hemorrhage')),
                ('ai_hysterectomy_other', models.BigIntegerField(default=0, verbose_name='Postpartum hysterectomy (other causes)')),
                ('ai_total', models.BigIntegerField(default=0, verbose_name='Total number of advanced interventions conducted')),
                ('aimfacilityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility Name')),
            ],
            options={
                'verbose_name': 'AIM-PPH',
                'verbose_name_plural': 'AIM-PPH',
            },
        ),
    ]
