# Generated by Django 5.1.4 on 2025-12-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0072_aimpph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'THEMATIC AREA', 'verbose_name_plural': 'THEMATIC AREA'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'HQIP ASSESSMENT', 'verbose_name_plural': 'HQIP ASSESSMENT'},
        ),
        migrations.AlterModelOptions(
            name='assessmenttype',
            options={'verbose_name': 'ASSESSMENT TYPE', 'verbose_name_plural': 'ASSESSMENT TYPE'},
        ),
        migrations.AlterModelOptions(
            name='assessor',
            options={'verbose_name': 'CLINICAL MENTORS', 'verbose_name_plural': 'CLINICAL MENTORS'},
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'verbose_name': 'HQIP CRITERIA', 'verbose_name_plural': 'THHQIP CRITERIA'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'DISTRICT', 'verbose_name_plural': 'DISTRICT'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'HEALTH FACILITY', 'verbose_name_plural': 'HEALTH FACILITY'},
        ),
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'verbose_name': 'HEALTH FACILITY TYPE', 'verbose_name_plural': 'HEALTH FACILITY TYPE'},
        ),
        migrations.AlterModelOptions(
            name='implementor',
            options={'verbose_name': 'IMPLEMENTER', 'verbose_name_plural': 'IMPLEMENTER'},
        ),
        migrations.AlterModelOptions(
            name='mentorshipdetails',
            options={'verbose_name': 'MENTORSHIP DETAIL', 'verbose_name_plural': 'STMENTORSHIP DETAIL'},
        ),
        migrations.AlterModelOptions(
            name='mentorshiptopics',
            options={'verbose_name': 'MENTORSHIP TOPIC', 'verbose_name_plural': 'MENTORSHIP TOPIC'},
        ),
        migrations.AlterModelOptions(
            name='mentorshipvisit',
            options={'verbose_name': 'MENTORSHIP VISIT', 'verbose_name_plural': 'MENTORSHIP VISIT'},
        ),
        migrations.AlterModelOptions(
            name='participationtype',
            options={'verbose_name': 'PARTICIPANT TYPE', 'verbose_name_plural': 'PARTICIPANT TYPE'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'STAFF PROFESSION', 'verbose_name_plural': 'STAFF PROFESSION'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'PROVINCE', 'verbose_name_plural': 'PROVINCE'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'HQIP SCORE', 'verbose_name_plural': 'THEMHQIP SCORE'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'HQIP SECTION', 'verbose_name_plural': 'THEMHQIP SECTION'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'STAFF JOB TITLE', 'verbose_name_plural': 'STAFF JOB TITLE'},
        ),
        migrations.AlterModelOptions(
            name='standards',
            options={'verbose_name': 'HQIP STANDARD', 'verbose_name_plural': 'THQIP STANDARD'},
        ),
        migrations.AlterModelOptions(
            name='thematicmentorship',
            options={'verbose_name': 'MENTORSHIP THEMATIC AREA', 'verbose_name_plural': 'MENTORSHIP THEMATIC AREA'},
        ),
        migrations.AlterModelOptions(
            name='trainingheader',
            options={'verbose_name': 'TRAINING TITLE', 'verbose_name_plural': 'PATRAINING TITLE'},
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='afiat_flag',
            field=models.BooleanField(verbose_name='AFIAT'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='bl_progress',
            field=models.CharField(verbose_name='Baseline and Progress'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='gre_month',
            field=models.CharField(verbose_name='Calender Month'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='gre_year',
            field=models.CharField(verbose_name='Calender Year'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='period',
            field=models.CharField(verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='shamsimonth',
            field=models.CharField(verbose_name='Afghanistan Month'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='shamsiyear',
            field=models.CharField(verbose_name='Afghanistan Year'),
        ),
        migrations.CreateModel(
            name='safesurgeryclinical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamsimonth', models.CharField(verbose_name='Afghanistan Month')),
                ('shamsiyear', models.CharField(verbose_name='Afghanistan Year')),
                ('period', models.CharField(verbose_name='Period')),
                ('bl_progress', models.CharField(verbose_name='Baseline and Progress')),
                ('gre_month', models.CharField(verbose_name='Calender Month')),
                ('gre_year', models.CharField(verbose_name='Calender Year')),
                ('afiat_flag', models.BooleanField(verbose_name='AFIAT')),
                ('total_cs', models.BigIntegerField(blank=True, null=True, verbose_name='Total Number of Cesarean Section')),
                ('total_deliv', models.BigIntegerField(blank=True, null=True, verbose_name='Total Number of Deliveries')),
                ('cs_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Cesarean Section Rate')),
                ('who_ssc_completed', models.BigIntegerField(blank=True, null=True, verbose_name='Number of WHO Surgical Safety Checklists completed')),
                ('who_ssc_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Surgical Safety Checklist completion rate')),
                ('safe_tracker_complete', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Safe Surgery Tracker with all fields completed')),
                ('safe_tracker_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Safe Surgery Tracker completion rate')),
                ('pph_cs_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Post-Partum Hemorrhage cases during or after CS')),
                ('pph_cs_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Cesarean PPH Rate (>500 ml)')),
                ('qbl_cs_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of C-Section cases with QBL performed & recorded')),
                ('qbl_cs_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='QBL performance rate during C-sections')),
                ('postop_fever_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of CS with post-operation fever (>38℃) requiring antibiotics')),
                ('postop_fever_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Post operation fever (>38℃) rate requiring antibiotics')),
                ('bladder_injury_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of cases of injury to bladder due to CS')),
                ('bladder_injury_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Injury to bladder rate due to CS')),
                ('bowel_injury_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of injury to bowel due to CS')),
                ('bowel_injury_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Injury to bowel rate due to CS')),
                ('hyst_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of hysterectomy during or after CS')),
                ('hyst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Hysterectomy rate during or after CS')),
                ('vag_clean_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of vaginal cleansing before CS')),
                ('vag_clean_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Vaginal cleansing rate')),
                ('foley_after_anes_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of Foley catheter applied after induction of anesthesia')),
                ('foley_after_anes_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='CS rate with Foley catheter after anesthesia induction')),
                ('abx_proph_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of CS with IV prophylactic antibiotic provided prior to CS')),
                ('abx_proph_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Antibiotic prophylaxis rate (15–60 minutes prior to incision) – Cefazolin or other cephalosporin according to availability')),
                ('skin_prep_num', models.BigIntegerField(blank=True, null=True, verbose_name='Number of CS with incision skin preparation performed')),
                ('skin_prep_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Rate of incision site skin preparation')),
                ('mat_death_pph_cs', models.BigIntegerField(blank=True, null=True, verbose_name='Number of maternal deaths due to PPH related to CS')),
                ('mat_death_other_cs', models.BigIntegerField(blank=True, null=True, verbose_name='Number of maternal deaths due to other causes related to CS')),
                ('mat_death_total', models.BigIntegerField(blank=True, null=True, verbose_name='Total number of maternal deaths related or not to CS')),
                ('aimfacilityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility Name')),
            ],
            options={
                'verbose_name': 'SAFE-SURGERY',
                'verbose_name_plural': 'SAFE-SURGERY',
            },
        ),
    ]
