# Generated by Django 5.1.4 on 2025-12-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0073_alter_area_options_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectobjective',
            name='ProjectGoal',
        ),
        migrations.RemoveField(
            model_name='projectoutput',
            name='ProjectObjective',
        ),
        migrations.RemoveField(
            model_name='qqmdomainindicator',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='tpm',
            name='domainindicator',
        ),
        migrations.RemoveField(
            model_name='tpm',
            name='facility',
        ),
        migrations.AlterModelOptions(
            name='safesurgeryclinical',
            options={'verbose_name': 'SAFE SURGERY', 'verbose_name_plural': 'SAFE SURGERY'},
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='IndicatorType',
        ),
        migrations.DeleteModel(
            name='ProjectGoal',
        ),
        migrations.DeleteModel(
            name='ProjectObjective',
        ),
        migrations.DeleteModel(
            name='ProjectOutput',
        ),
        migrations.DeleteModel(
            name='Qqmdomain',
        ),
        migrations.DeleteModel(
            name='QqmdomainIndicator',
        ),
        migrations.DeleteModel(
            name='tpm',
        ),
    ]
