# Generated by Django 5.1.4 on 2025-12-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0074_remove_projectobjective_projectgoal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gancenrollment',
            name='cohortname',
        ),
        migrations.RemoveField(
            model_name='gancthirdsession',
            name='registerid',
        ),
        migrations.RemoveField(
            model_name='gancsecondsession',
            name='registerid',
        ),
        migrations.RemoveField(
            model_name='gancfirstsession',
            name='registerid',
        ),
        migrations.RemoveField(
            model_name='gancohort',
            name='facilityname',
        ),
        migrations.DeleteModel(
            name='Qiccriterialist',
        ),
        migrations.AlterModelOptions(
            name='mentorshipdetails',
            options={'verbose_name': 'MENTORSHIP DETAIL', 'verbose_name_plural': 'MENTORSHIP DETAIL'},
        ),
        migrations.AlterModelOptions(
            name='mpdsr',
            options={'verbose_name': 'MPDSR', 'verbose_name_plural': 'MPDSR'},
        ),
        migrations.AlterModelOptions(
            name='participanteducation',
            options={'verbose_name': 'PARTICIPANT EDUCATION', 'verbose_name_plural': 'DIPARTICIPANT EDUCATION'},
        ),
        migrations.AlterModelOptions(
            name='participantposition',
            options={'verbose_name': 'PARTICIPANT POSITION', 'verbose_name_plural': 'PARTICIPANT POSITION'},
        ),
        migrations.AlterModelOptions(
            name='qicdataset',
            options={'verbose_name': 'QIC', 'verbose_name_plural': 'QIC'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'HQIP SCORE', 'verbose_name_plural': 'HQIP SCORE'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'HQIP SECTION', 'verbose_name_plural': 'HQIP SECTION'},
        ),
        migrations.AlterModelOptions(
            name='standards',
            options={'verbose_name': 'HQIP STANDARD', 'verbose_name_plural': 'HQIP STANDARD'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'TRAINING', 'verbose_name_plural': 'TRAINING'},
        ),
        migrations.AlterModelOptions(
            name='trainingheader',
            options={'verbose_name': 'TRAINING TITLE', 'verbose_name_plural': 'TRAINING TITLE'},
        ),
        migrations.DeleteModel(
            name='Gancthirdsession',
        ),
        migrations.DeleteModel(
            name='Gancsecondsession',
        ),
        migrations.DeleteModel(
            name='Gancenrollment',
        ),
        migrations.DeleteModel(
            name='Gancfirstsession',
        ),
        migrations.DeleteModel(
            name='Gancohort',
        ),
    ]
