# Generated by Django 5.1.4 on 2025-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0075_remove_gancenrollment_cohortname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='abx_proph_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of CS with IV prophylactic antibiotic provided prior to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='abx_proph_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Antibiotic prophylaxis rate (15–60 minutes prior to incision) – Cefazolin or other cephalosporin according to availability'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='bladder_injury_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of cases of injury to bladder due to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='bladder_injury_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Injury to bladder rate due to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='bowel_injury_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of injury to bowel due to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='bowel_injury_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Injury to bowel rate due to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='cs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Cesarean Section Rate'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='foley_after_anes_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of Foley catheter applied after induction of anesthesia'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='foley_after_anes_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='CS rate with Foley catheter after anesthesia induction'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='hyst_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of hysterectomy during or after CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='hyst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Hysterectomy rate during or after CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='mat_death_other_cs',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of maternal deaths due to other causes related to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='mat_death_pph_cs',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of maternal deaths due to PPH related to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='mat_death_total',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total number of maternal deaths related or not to CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='postop_fever_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of CS with post-operation fever (>38℃) requiring antibiotics'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='postop_fever_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Post operation fever (>38℃) rate requiring antibiotics'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='pph_cs_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of Post-Partum Hemorrhage cases during or after CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='pph_cs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Cesarean PPH Rate (>500 ml)'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='qbl_cs_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of C-Section cases with QBL performed & recorded'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='qbl_cs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='QBL performance rate during C-sections'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='safe_tracker_complete',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of Safe Surgery Tracker with all fields completed'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='safe_tracker_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Safe Surgery Tracker completion rate'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='skin_prep_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of CS with incision skin preparation performed'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='skin_prep_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Rate of incision site skin preparation'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='total_cs',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total Number of Cesarean Section'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='total_deliv',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total Number of Deliveries'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='vag_clean_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of vaginal cleansing before CS'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='vag_clean_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Vaginal cleansing rate'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='who_ssc_completed',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of WHO Surgical Safety Checklists completed'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='who_ssc_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Surgical Safety Checklist completion rate'),
        ),
    ]
