# Generated by Django 5.1.4 on 2025-12-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0076_alter_safesurgeryclinical_abx_proph_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessor',
            options={'verbose_name': 'CLINICAL MENTOR', 'verbose_name_plural': 'CLINICAL MENTOR'},
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'verbose_name': 'HQIP CRITERIA', 'verbose_name_plural': 'HQIP CRITERIA'},
        ),
        migrations.AlterModelOptions(
            name='participanteducation',
            options={'verbose_name': 'PARTICIPANT EDUCATION', 'verbose_name_plural': 'PARTICIPANT EDUCATION'},
        ),
    ]
