# Generated by Django 5.1.4 on 2025-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0078_alter_province_name_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimpee',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
