# Generated by Django 5.1.4 on 2025-12-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0079_aimpee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimpph',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='safesurgeryclinical',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
