# Generated by Django 5.1.4 on 2026-01-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0080_aimpph_status_safesurgeryclinical_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'MENTEE', 'verbose_name_plural': 'MENTEE'},
        ),
        migrations.AddField(
            model_name='score',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
