# Generated by Django 5.1.4 on 2026-01-02 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0081_alter_staff_options_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scorefk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.score'),
        ),
    ]
