# Generated by Django 5.1.4 on 2026-01-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0082_alter_assessment_scorefk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQIPAssessmentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentdate', models.DateField()),
                ('assessmentend_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('areafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.area')),
                ('assesorfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor')),
                ('assessmenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessmenttype')),
                ('facilityfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
                ('implementorfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.implementor')),
            ],
        ),
        migrations.CreateModel(
            name='HQIPAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('criteriafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.criteria')),
                ('scorefk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.score')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hiva.hqipassessmentheader')),
            ],
            options={
                'verbose_name': 'HQIP ASSESSMENT',
                'verbose_name_plural': 'HQIP ASSESSMENT',
            },
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.AddConstraint(
            model_name='hqipassessmentheader',
            constraint=models.UniqueConstraint(fields=('facilityfk', 'assessmenttype', 'assessmentdate', 'areafk'), name='uniq_hdr_fac_type_date_area'),
        ),
        migrations.AddConstraint(
            model_name='hqipassessment',
            constraint=models.UniqueConstraint(fields=('header', 'criteriafk'), name='uniq_line_per_criteria'),
        ),
    ]
