# Generated by Django 5.1.4 on 2026-01-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0083_hqipassessmentheader_hqipassessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqipassessment',
            name='scorefk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.score'),
        ),
    ]
