# Generated by Django 5.1.4 on 2026-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0084_alter_hqipassessment_scorefk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hqipassessment',
            options={'verbose_name': 'HQIP ASSESSMENT DETAILS', 'verbose_name_plural': 'HQIP ASSESSMENT DETAILS'},
        ),
        migrations.AlterModelOptions(
            name='hqipassessmentheader',
            options={'verbose_name': 'HQIP ASSESSMENT', 'verbose_name_plural': 'HQIP ASSESSMENT'},
        ),
        migrations.AlterField(
            model_name='hqipassessment',
            name='remarks',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='remarks',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
