# Generated by Django 5.1.4 on 2026-01-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0085_alter_hqipassessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hqipassessment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='hqipassessmentheader',
            name='remarks',
        ),
    ]
