# Generated by Django 5.1.4 on 2026-01-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0086_remove_hqipassessment_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='areafk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.area', verbose_name='Thematic Area'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='assesorfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor', verbose_name='Assessor'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='assessmentdate',
            field=models.DateField(verbose_name='Assessment Start Date'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='assessmentend_date',
            field=models.DateField(verbose_name='Assessment End Date'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='assessmenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.assessmenttype', verbose_name='Assessment Type'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='facilityfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='implementorfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.implementor', verbose_name='Implementor'),
        ),
    ]
