# Generated by Django 5.1.4 on 2026-01-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0087_alter_hqipassessmentheader_areafk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqipassessmentheader',
            name='assessmentteam',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hqipassessmentheader',
            name='is_RCAduringtheassessment',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Root Cause Assessment (RCA) conducted during the assessment'),
        ),
        migrations.AddField(
            model_name='implementor',
            name='provinceimplementor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.province'),
        ),
    ]
