# Generated by Django 5.1.4 on 2026-01-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0088_hqipassessmentheader_assessmentteam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='assessmentteam',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Assessment Team'),
        ),
    ]
