# Generated by Django 5.1.4 on 2026-01-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0089_alter_hqipassessmentheader_assessmentteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshiptopics',
            name='thematicfk',
        ),
        migrations.RemoveField(
            model_name='mentorshipvisit',
            name='facilityfk',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hfname',
        ),
        migrations.RemoveField(
            model_name='assessor',
            name='Status',
        ),
        migrations.AddField(
            model_name='facility',
            name='kmc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nbcc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='sncu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Thematic Area'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='continuetophase2',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Continued to Phase Two'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(True, 'Female'), (False, 'Male')], default=True, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Assessor Name'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.TextField(verbose_name='Verification Criteria'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.TextField(max_length=200, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='aimphase',
            field=models.IntegerField(blank=True, null=True, verbose_name='AIM Phase'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='skilllab',
            field=models.BooleanField(blank=True, default=False, verbose_name='Skill Lab'),
        ),
        migrations.AlterField(
            model_name='implementor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Service Provider(NGO)'),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.TextField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='name',
            field=models.TextField(verbose_name='Standard'),
        ),
        migrations.DeleteModel(
            name='Mentorshipdetails',
        ),
        migrations.DeleteModel(
            name='MentorshipTopics',
        ),
        migrations.DeleteModel(
            name='ThematicMentorship',
        ),
        migrations.DeleteModel(
            name='Mentorshipvisit',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
