# Generated by Django 5.1.4 on 2026-01-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0090_remove_mentorshiptopics_thematicfk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='Status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Assessment Type'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.TextField(max_length=200, unique=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.TextField(max_length=200, unique=True, verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='implementor',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Service Provider(NGO)'),
        ),
    ]
