# Generated by Django 5.1.4 on 2026-01-08 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0091_assessor_status_alter_assessmenttype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hqipassessmentheader',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='hqipassessmentheader',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hqip_assessments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hqipassessmentheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hqipassessmentheader',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hqip_assessments_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
