# Generated by Django 5.1.4 on 2026-01-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0092_hqipassessmentheader_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessor',
            old_name='Status',
            new_name='status',
        ),
    ]
