# Generated by Django 5.1.4 on 2026-01-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0093_rename_status_assessor_status'),
        ('hiva', '0094_add_assessor_gender_column'),
    ]

    operations = [
    ]
