# Generated by Django 5.1.4 on 2026-01-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0095_merge_20260108_1010'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE hiva_assessor
                ADD COLUMN IF NOT EXISTS continuetophase2 boolean NULL;
            """,
            reverse_sql="""
                ALTER TABLE hiva_assessor
                DROP COLUMN IF EXISTS continuetophase2;
            """,
        ),
    ]