# Generated by Django 5.1.4 on 2026-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0096_add_assessor_continuetophase2_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Position')),
            ],
            options={
                'verbose_name': 'STAFF PROFESSION',
                'verbose_name_plural': 'STAFF PROFESSION',
            },
        ),
    ]
