# Generated by Django 5.1.4 on 2026-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0097_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='kmc',
            field=models.BooleanField(blank=True, null=True, verbose_name='KMC'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='nbcc',
            field=models.BooleanField(blank=True, null=True, verbose_name='NBCC'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sncu',
            field=models.BooleanField(blank=True, null=True, verbose_name='SNCU'),
        ),
    ]
