# Generated by Django 5.1.4 on 2026-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0098_alter_facility_kmc_alter_facility_nbcc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpdsr',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mpdsr',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='monthmpdsr',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='January', max_length=200, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='yearmpdsr',
            field=models.IntegerField(choices=[('2026', '2026'), ('2027', '2027')], default=2025, verbose_name='Year'),
        ),
    ]
