# Generated by Django 5.1.4 on 2026-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0099_remove_mpdsr_image_remove_mpdsr_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdsr',
            name='causeofmaternaldeaths_m',
            field=models.TextField(max_length=200, verbose_name='Cause of maternal deaths'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='causeofneonataldeath_n',
            field=models.TextField(max_length=200, verbose_name='Cause of neonatal death'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='interventionperformed',
            field=models.TextField(max_length=200, verbose_name='Intervention performed'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='recfromMPDSRcommittee',
            field=models.TextField(max_length=500, verbose_name='Recommendation from MPDSR committee'),
        ),
    ]
