# Generated by Django 5.1.4 on 2026-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0100_alter_mpdsr_causeofmaternaldeaths_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdsr',
            name='yearmpdsr',
            field=models.IntegerField(choices=[(2026, '2026'), (2027, '2027')], default=2026, verbose_name='Year'),
        ),
    ]
