# Generated by Django 5.1.4 on 2026-01-11 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0101_alter_mpdsr_yearmpdsr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpdsr',
            options={'ordering': ['-yearmpdsr', '-monthmpdsr', 'facilityname'], 'verbose_name': 'MPDSR', 'verbose_name_plural': 'MPDSR'},
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpdsr_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpdsr_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='monthmpdsr',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=2, verbose_name='Month'),
        ),
        migrations.AddConstraint(
            model_name='mpdsr',
            constraint=models.UniqueConstraint(fields=('facilityname', 'yearmpdsr', 'monthmpdsr'), name='uniq_facility_year_month_mpdsr'),
        ),
    ]
