# Generated by Django 5.1.4 on 2026-01-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0102_alter_mpdsr_options_mpdsr_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='namedari',
        ),
        migrations.AddField(
            model_name='area',
            name='area_namedari',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Thematic Area Dari'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_namepashto',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Thematic Area Pashto'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='criteria_namedari',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Criteria Dari'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='criteria_namepashto',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Criteria Pashto'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_namedari',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Score Dari'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_namepashto',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Score Pashto'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_namedari',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Section Dari'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_namepashto',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Section Pashto'),
        ),
        migrations.AddField(
            model_name='standards',
            name='standard_namedari',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Standard Dari'),
        ),
        migrations.AddField(
            model_name='standards',
            name='standard_namepashto',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Standard Pashto'),
        ),
    ]
