# Generated by Django 5.1.4 on 2026-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0103_remove_criteria_namedari_area_area_namedari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='assessmentteam',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Assessment Team'),
        ),
        migrations.AlterField(
            model_name='hqipassessmentheader',
            name='is_RCAduringtheassessment',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='RCA conducted'),
        ),
    ]
