# Generated by Django 5.1.4 on 2026-01-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0104_alter_hqipassessmentheader_assessmentteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoChildbirthChecklistMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamsi_month', models.CharField(verbose_name='Afghanistan Month')),
                ('shamsi_year', models.CharField(verbose_name='Afghanistan Year')),
                ('period', models.CharField(verbose_name='Period')),
                ('bl_progress', models.CharField(verbose_name='Baseline and Progress')),
                ('gre_month', models.CharField(verbose_name='Calender Month')),
                ('gre_year', models.CharField(verbose_name='Calender Year')),
                ('afiat_flag', models.BooleanField(verbose_name='AFIAT')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total number of Deliveries (normal/assisted/c-sections)')),
                ('files_selected', models.PositiveIntegerField(default=0, help_text='Expected range: 0–20.', verbose_name='Out of total number of deliveries in the month, select RANDOMLY up to 20 patient files and record number of files selected')),
                ('sec1_complete', models.PositiveIntegerField(default=0, verbose_name='Number of section 1 of the WHO childbirth Checklists completely filled out')),
                ('cervix_ge4_admission', models.PositiveIntegerField(default=0, verbose_name='Number of patient files selected with pregnant women presenting cervix ≥4 cms at admission')),
                ('partograph_started_ge4', models.PositiveIntegerField(default=0, verbose_name='Number of partographs started at cervix ≥4 cms at admission')),
                ('sec2_complete', models.PositiveIntegerField(default=0, verbose_name='Number of section 2 of the WHO childbirth Checklists completely filled out')),
                ('newborn_supplies_5_available', models.PositiveIntegerField(default=0, verbose_name='Number of deliveries with the 5 essential supplies available at bedside for newborn')),
                ('sec3_complete', models.PositiveIntegerField(default=0, verbose_name='Number of section 3 of the WHO childbirth Checklists completely filled out')),
                ('bf_s2s_first_hour', models.PositiveIntegerField(default=0, verbose_name='Number of deliveries which started breastfeeding and skin-to-skin contact during first hour (if mother and baby are well).')),
                ('sec4_complete', models.PositiveIntegerField(default=0, verbose_name='Number of section 4 of the WHO childbirth Checklists completely filled out')),
                ('abx_need_checked_newborn', models.PositiveIntegerField(default=0, verbose_name='Number of deliveries for which the need for antibiotic for newborn was checked before discharge')),
                ('all4_sections_complete', models.PositiveIntegerField(default=0, verbose_name='Number of patient files with the 4 sections of the WHO childbirth Checklists completely filled out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility Name')),
            ],
            options={
                'verbose_name': 'WHO Childbirth Checklist (Monthly)',
                'verbose_name_plural': 'WHO Childbirth Checklist (Monthly)',
                'ordering': ('-shamsi_year', '-shamsi_month', 'facility_name'),
                'unique_together': {('facility_name', 'shamsi_year', 'shamsi_month')},
            },
        ),
    ]
