# Generated by Django 5.1.4 on 2026-01-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0105_whochildbirthchecklistmonthly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whochildbirthchecklistmonthly',
            options={'ordering': ('-shamsi_year', '-shamsi_month', 'facility_name'), 'verbose_name': 'WHO CHILDBIRTH CHECKLIST', 'verbose_name_plural': 'WHO CHILDBIRTH CHECKLIST'},
        ),
    ]
