# Generated by Django 5.1.4 on 2026-01-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0106_alter_whochildbirthchecklistmonthly_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdsr',
            name='yearmpdsr',
            field=models.IntegerField(choices=[(2026, '2026'), (2026, '2026'), (2027, '2027')], default=2026, verbose_name='Year'),
        ),
    ]
