# Generated by Django 5.1.4 on 2026-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0107_alter_mpdsr_yearmpdsr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimpee',
            old_name='num_anc_preg_seen',
            new_name='anc_total_seen',
        ),
        migrations.RenameField(
            model_name='aimpee',
            old_name='comp_eclamptic_coma',
            new_name='eclamptic_coma',
        ),
        migrations.RenameField(
            model_name='aimpee',
            old_name='comp_eclamptic_seizure',
            new_name='eclamptic_seizure',
        ),
        migrations.RenameField(
            model_name='aimpee',
            old_name='comp_hellp',
            new_name='hellp_syndrome',
        ),
        migrations.RenameField(
            model_name='aimpee',
            old_name='comp_placental_abruption',
            new_name='placental_abruption',
        ),
        migrations.RenameField(
            model_name='aimpee',
            old_name='comp_pulmonary_edema',
            new_name='pulmonary_edema',
        ),
        migrations.RenameField(
            model_name='aimpee',
            old_name='comp_total',
            new_name='total_complications',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_aortic_compression',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_blynch_ual',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_hysterectomy_other',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_lac_repair',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_nasg',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_pph_hysterectomy',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_ruptured_uterus_repair',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_total',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='ai_ubt',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='comp_iufd',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='comp_pres',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='comp_renal_failure',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='comp_stroke',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='comp_thrombocytopenia',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='maternal_death_spe_e',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_anc_bp_taken',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_anc_pree_admit',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_anc_pree_dx',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_chronic_htn_superimposed_pe',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_eclampsia_admit_before_delivery',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_eclampsia_at_birth',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_eclampsia_deliv_12h',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_gest_htn',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_opd_pree_dx_md',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_opd_pree_twice_week',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_opd_pree_weekly_labs',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_severe_pe_e_bp160',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_severe_pe_e_bp160_tx1h',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_spe_admit_before_delivery',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_spe_at_birth',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_spe_deliv_24h',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_spe_e_fu_3d',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_spe_e_mgso4_1h',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='num_spe_e_pp_dx',
        ),
        migrations.RemoveField(
            model_name='aimpee',
            name='pct_opd_pree_weekly_labs',
        ),
        migrations.AddField(
            model_name='aimpee',
            name='anc_bp_measured',
            field=models.BigIntegerField(default=0, verbose_name='Number of ANC women with blood pressure measured'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='chronic_htn_superimposed_pree',
            field=models.BigIntegerField(default=0, verbose_name='Chronic hypertension with superimposed Pre-Eclampsia'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='eclampsia_admissions_before_delivery',
            field=models.BigIntegerField(default=0, verbose_name='Admissions with Eclampsia before delivery (incl. referrals)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='eclampsia_delivered_within_12hrs',
            field=models.BigIntegerField(default=0, verbose_name='Eclampsia deliveries within 12 hours of admission'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='gestational_hypertension',
            field=models.BigIntegerField(default=0, verbose_name='Gestational hypertension cases'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='intrauterine_fetal_death',
            field=models.BigIntegerField(default=0, verbose_name='Intrauterine fetal death'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='magnesium_sulfate_within_1hr',
            field=models.BigIntegerField(default=0, verbose_name='SPE/Eclampsia patients receiving Magnesium Sulfate within 1 hour'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='maternal_death',
            field=models.BigIntegerField(default=0, verbose_name='Maternal deaths due to SPE or Eclampsia'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='opd_pree_seen_by_md',
            field=models.BigIntegerField(default=0, verbose_name='OPD patients diagnosed with Pre-Eclampsia seen by MD'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='opd_pree_twice_weekly_followup',
            field=models.BigIntegerField(default=0, verbose_name='Pre-Eclampsia outpatients returning twice weekly'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='opd_pree_weekly_lab_testing',
            field=models.BigIntegerField(default=0, verbose_name='Pre-Eclampsia outpatients receiving weekly lab testing'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='opd_pree_weekly_lab_testing_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentage receiving weekly lab testing'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='post_delivery_followup_3days',
            field=models.BigIntegerField(default=0, verbose_name='SPE/Eclampsia patients followed up within 3 days after discharge'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='postpartum_pree_eclampsia',
            field=models.BigIntegerField(default=0, verbose_name='Pre-Eclampsia/Eclampsia diagnosed during postpartum period'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='pree_admitted_from_anc',
            field=models.BigIntegerField(default=0, verbose_name='Pre-Eclampsia patients admitted from ANC'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='preeclampsia_diagnosed',
            field=models.BigIntegerField(default=0, verbose_name='Number of ANC women diagnosed with Pre-Eclampsia (BP >140/90 + proteinuria)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='pres',
            field=models.BigIntegerField(default=0, verbose_name='PRES'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='renal_failure',
            field=models.BigIntegerField(default=0, verbose_name='Renal failure'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='severe_pree_antihypertensive_within_1hr',
            field=models.BigIntegerField(default=0, verbose_name='Severe Pre-E/Eclampsia patients receiving antihypertensive within 1 hour'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='severe_pree_or_eclampsia',
            field=models.BigIntegerField(default=0, verbose_name='Number of patients with Severe Pre-Eclampsia or Eclampsia (BP ≥160/110)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='spe_admissions_before_delivery',
            field=models.BigIntegerField(default=0, verbose_name='Admissions with Severe Pre-Eclampsia before delivery (incl. referrals)'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='spe_delivered_within_24hrs',
            field=models.BigIntegerField(default=0, verbose_name='Severe Pre-Eclampsia deliveries within 24 hours of admission'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='stroke',
            field=models.BigIntegerField(default=0, verbose_name='Stroke'),
        ),
        migrations.AddField(
            model_name='aimpee',
            name='thrombocytopenia',
            field=models.BigIntegerField(default=0, verbose_name='Thrombocytopenia (non-HELLP)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
    ]
