# Generated by Django 5.1.4 on 2026-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0108_rename_num_anc_preg_seen_aimpee_anc_total_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimpph',
            name='pph_medication_uterotonic',
            field=models.BigIntegerField(default=0, verbose_name='PPH management by medication (uterotonic)'),
        ),
        migrations.AddField(
            model_name='aimpph',
            name='pph_total',
            field=models.BigIntegerField(default=0, verbose_name='10. Total number of PPH cases (sum of indicators 6–9)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='anc_bp_measured',
            field=models.BigIntegerField(default=0, verbose_name='2. Number of ANC women with blood pressure measured'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='anc_total_seen',
            field=models.BigIntegerField(default=0, verbose_name='1. Number of pregnant women seen in ANC'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='chronic_htn_superimposed_pree',
            field=models.BigIntegerField(default=0, verbose_name='14. Number of patients with chronic hypertension* with superimposed pre-eclampsia'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='eclampsia_admissions_before_delivery',
            field=models.BigIntegerField(default=0, verbose_name='12. Number of patients admitted to a HFs with  Eclampsia before delivery, birth (including referrals in)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='eclampsia_delivered_within_12hrs',
            field=models.BigIntegerField(default=0, verbose_name='17. Number of Eclampsia patients who delivered within 12 hours of admission'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='eclamptic_coma',
            field=models.BigIntegerField(default=0, verbose_name='29. Eclamptic coma'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='eclamptic_seizure',
            field=models.BigIntegerField(default=0, verbose_name='22. Eclamptic seizure'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='gestational_hypertension',
            field=models.BigIntegerField(default=0, verbose_name='15. Number of patients with Gestational hypertension*'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='hellp_syndrome',
            field=models.BigIntegerField(default=0, verbose_name='25. HELLP syndrome'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='intrauterine_fetal_death',
            field=models.BigIntegerField(default=0, verbose_name='27. Intrauterine fetal death'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='magnesium_sulfate_within_1hr',
            field=models.BigIntegerField(default=0, verbose_name='13. Number of patients WITH SEVERE PRE-ECLAMPSIA or Eclampsia who received Magnesium Sulfate within one hour of the diagnosis'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='maternal_death',
            field=models.BigIntegerField(default=0, verbose_name='31. Maternal deaths due to SPE or Eclampsia'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='opd_pree_seen_by_md',
            field=models.BigIntegerField(default=0, verbose_name='6. Number of outpatients diagnosed in OPD with Pre-Eclampsia by MD(AAC member must check that the patient with high BP is seen by the MD in OPD)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='opd_pree_twice_weekly_followup',
            field=models.BigIntegerField(default=0, verbose_name='7. Number of outpatients seen in ANC/OPD ward with Pre-Eclampsia who returned to ANC/OPD ward twice a week'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='opd_pree_weekly_lab_testing',
            field=models.BigIntegerField(default=0, verbose_name='8. Number of outpatients seen in ANC/OPD ward with Pre-Eclampsia who received weekly laboratory testing'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='opd_pree_weekly_lab_testing_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='9. Percentage of outpatients seen in ANC/OPD with Pre-Eclampsia who received weekly laboratory testing'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='placental_abruption',
            field=models.BigIntegerField(default=0, verbose_name='28. Placental abruption'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='post_delivery_followup_3days',
            field=models.BigIntegerField(default=0, verbose_name='18. Number of patients with SPE or eclampsia who had a follow up visit within 3 days after the delivery discharge'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='postpartum_pree_eclampsia',
            field=models.BigIntegerField(default=0, verbose_name='19. Number of patients with SPE or eclampsia diagnosed during the post-partum period'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='pree_admitted_from_anc',
            field=models.BigIntegerField(default=0, verbose_name='10. Number of Patients with Pre-E diagnosed in ANC clinic who required admision (Admitted patients)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='preeclampsia_diagnosed',
            field=models.BigIntegerField(default=0, verbose_name='3. Number of ANC women diagnosed with Pre-Eclampsia (BP >140/90 + proteinuria)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='pres',
            field=models.BigIntegerField(default=0, verbose_name='26. PRES (Posterior Reversible Encephalopathy Syndrome)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='pulmonary_edema',
            field=models.BigIntegerField(default=0, verbose_name='21. Pulmonary edema'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='renal_failure',
            field=models.BigIntegerField(default=0, verbose_name='20. Renal Failure (LESS THAN 30 ml/hr for 4 hours despite fluid challenge)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='severe_pree_antihypertensive_within_1hr',
            field=models.BigIntegerField(default=0, verbose_name='5. Number of patients with Severe Pre-eclampsia or Eclampsia WITH BP > 160 Systolic OR 110 diastolic who received an antihypertensive medication within one hour of the diagnosis'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='severe_pree_or_eclampsia',
            field=models.BigIntegerField(default=0, verbose_name='4. Number of patients with Severe Pre-Eclampsia or Eclampsia WITH BP > 160 Systolic OR 110 diastolic'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='spe_admissions_before_delivery',
            field=models.BigIntegerField(default=0, verbose_name='11. Number of patients admitted to HFs with SEVERE PRE-ECLAMPSIA (SPE) before delivery, birth (including referrals in)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='spe_delivered_within_24hrs',
            field=models.BigIntegerField(default=0, verbose_name='16. Number of Severe Pre-eclampsia patients who delivered within 24 hours of admission'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='stroke',
            field=models.BigIntegerField(default=0, verbose_name='23. Stroke (Cerebral Hemorrhage or Blood clot in brain)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='thrombocytopenia',
            field=models.BigIntegerField(default=0, verbose_name='24. Thrombocytopenia (non-HELLP)'),
        ),
        migrations.AlterField(
            model_name='aimpee',
            name='total_complications',
            field=models.BigIntegerField(default=0, verbose_name='30. Total complications due to SPE and Eclampsia'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='antepartum_hemorrhage',
            field=models.BigIntegerField(default=0, verbose_name='5. Number of Antepartum Hemorrhage (Abruption, Placenta Previa)'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='births_csection',
            field=models.BigIntegerField(default=0, verbose_name='3. Number of births - by C-sections'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='births_vaginal',
            field=models.BigIntegerField(default=0, verbose_name='2. Number of births - by vaginal delivery'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='oxytocin_immediate',
            field=models.BigIntegerField(default=0, verbose_name='4. Number of patients receiving oxytocin immediately after birth'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='pph_cs_1000_plus',
            field=models.BigIntegerField(default=0, verbose_name='7. Number of Postpartum Hemorrhage (PPH) - after Cesarean delivery (≥1000 cc)'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='pph_referral_in_aim',
            field=models.BigIntegerField(default=0, verbose_name='9. Number of Postpartum Hemorrhage (PPH) referrals in from AIM facilities'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='pph_referral_in_outside_aim',
            field=models.BigIntegerField(default=0, verbose_name='8. Number of Postpartum Hemorrhage (PPH) referrals in from outside of AIM facilities'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='pph_vaginal_501_999',
            field=models.BigIntegerField(default=0, verbose_name='6. Number of Postpartum Hemorrhage (PPH) - after vaginal delivery (501–999 cc)'),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='aimpph',
            name='total_births',
            field=models.BigIntegerField(default=0, verbose_name='1. Number of ALL births (log book)'),
        ),
    ]
