# Generated by Django 5.1.4 on 2026-03-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0109_aimpph_pph_medication_uterotonic_aimpph_pph_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name='Father_name')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7, null=True, verbose_name='Gender')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Staff Code')),
                ('tazkira_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tazkira Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('year_of_birth', models.IntegerField(blank=True, null=True, verbose_name='Year of Birth')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('record_status', models.IntegerField(default=1, verbose_name='Record Status')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_staffs', to='hiva.facility', verbose_name='Facility')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_staff_positions', to='hiva.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'FACILITY STAFF',
                'verbose_name_plural': 'FACILITY STAFF',
                'db_table': 'FacilityStaffs',
            },
        ),
        migrations.CreateModel(
            name='QICommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Head', 'Head'), ('Member', 'Member'), ('Focalpoint', 'Focalpoint'), ('Other', 'Other')], max_length=50, verbose_name='Committee Role')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated By')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('record_status', models.IntegerField(default=1, verbose_name='Record Status')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qi_committees', to='hiva.facility', verbose_name='HEALTH FACILITY')),
                ('facility_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qi_committee_memberships', to='hiva.facilitystaff', verbose_name='HEALTH FACILITY STAFF')),
            ],
            options={
                'verbose_name': 'QI COMMITTEE MEMBERS',
                'verbose_name_plural': 'QI COMMITTEE MEMBERS',
                'db_table': 'QICommittee',
            },
        ),
    ]
