# Generated by Django 5.1.4 on 2026-03-12 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0111_facilitystaff_created_by_facilitystaff_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qicommittee',
            options={'verbose_name': 'QIC MEMBERS', 'verbose_name_plural': 'QIC MEMBERS'},
        ),
        migrations.AlterField(
            model_name='facilitystaff',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilitystaff',
            name='record_status',
            field=models.IntegerField(default=1, editable=False, verbose_name='Record Status'),
        ),
        migrations.AlterField(
            model_name='facilitystaff',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilitystaff',
            name='verified',
            field=models.BooleanField(default=True, editable=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='qicommittee',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qicommittee',
            name='record_status',
            field=models.IntegerField(default=1, editable=False, verbose_name='Record Status'),
        ),
        migrations.AlterField(
            model_name='qicommittee',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
