# Generated by Django 5.1.4 on 2026-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0112_alter_qicommittee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpdsr',
            name='maternal_death_cause_category',
            field=models.CharField(blank=True, choices=[('hemorrhage', 'Obstetric hemorrhage'), ('hypertensive', 'Hypertensive disorders in pregnancy'), ('sepsis', 'Sepsis / infection'), ('obstructed_rupture', 'Obstructed labor / uterine rupture'), ('abortion', 'Abortion-related complications'), ('embolism', 'Embolism'), ('indirect', 'Indirect medical cause'), ('unknown', 'Unknown / under investigation'), ('other', 'Other specified cause')], help_text='Structured category for new records. Leave blank if no maternal death reported.', max_length=40, null=True, verbose_name='Maternal death cause category'),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='maternal_death_contributing_factor',
            field=models.CharField(blank=True, choices=[('delay_seek_care', 'Delay in deciding to seek care'), ('delay_reach_facility', 'Delay in reaching facility'), ('delay_receive_care', 'Delay in receiving appropriate care'), ('lack_medicines', 'Lack of essential medicines'), ('lack_blood', 'Lack of blood / transfusion service'), ('lack_equipment', 'Lack of equipment / supplies'), ('referral_delay', 'Referral delay'), ('staffing_gap', 'Human resource / staffing gap'), ('monitoring_gap', 'Monitoring / early detection gap'), ('clinical_management_gap', 'Gap in timely clinical management'), ('documentation_gap', 'Documentation gap'), ('community_awareness_gap', 'Community awareness gap'), ('other_system_gap', 'Other system gap')], help_text='Main contributing factor identified through no-blame MPDSR review.', max_length=50, null=True, verbose_name='Maternal death contributing factor'),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='maternal_death_place',
            field=models.CharField(blank=True, choices=[('home', 'At home'), ('in_transit', 'On the way / in transit'), ('facility', 'Health facility'), ('referral_facility', 'Referral facility'), ('unknown', 'Unknown')], max_length=30, null=True, verbose_name='Place of maternal death'),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='maternal_death_preventability',
            field=models.CharField(blank=True, choices=[('likely_preventable', 'Likely preventable'), ('possibly_preventable', 'Possibly preventable'), ('not_preventable', 'Not preventable'), ('unclear', 'Unclear')], max_length=30, null=True, verbose_name='Maternal death preventability'),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='maternal_death_specific_cause',
            field=models.CharField(blank=True, choices=[('pph', 'Postpartum hemorrhage (PPH)'), ('uterine_atony', 'Uterine atony'), ('abruptio_placenta', 'Abruptio placenta'), ('placenta_previa', 'Placenta previa'), ('retained_placenta', 'Retained placenta'), ('other_hemorrhage', 'Other obstetric hemorrhage'), ('severe_pre_eclampsia', 'Severe pre-eclampsia'), ('eclampsia', 'Eclampsia'), ('hellp', 'HELLP syndrome'), ('other_hypertensive', 'Other hypertensive disorder'), ('puerperal_sepsis', 'Puerperal sepsis'), ('post_abortion_sepsis', 'Post-abortion sepsis'), ('postoperative_infection', 'Postoperative infection'), ('other_sepsis', 'Other maternal infection'), ('obstructed_labor', 'Obstructed labor'), ('prolonged_labor', 'Prolonged labor'), ('uterine_rupture', 'Uterine rupture'), ('other_obstructed_rupture', 'Other labor-related complication'), ('abortion_hemorrhage', 'Hemorrhage after abortion'), ('unsafe_abortion', 'Unsafe abortion complication'), ('incomplete_abortion', 'Incomplete abortion complication'), ('other_abortion', 'Other abortion-related complication'), ('pulmonary_embolism', 'Pulmonary embolism'), ('amniotic_fluid_embolism', 'Amniotic fluid embolism'), ('other_embolism', 'Other embolism'), ('severe_anemia', 'Severe anemia'), ('cardiac_disease', 'Cardiac disease'), ('respiratory_disease', 'Respiratory disease / COPD'), ('liver_disease_pregnancy', 'Liver disease in pregnancy'), ('renal_disease', 'Renal disease'), ('malaria', 'Malaria'), ('tuberculosis', 'Tuberculosis'), ('diabetes', 'Diabetes complication'), ('other_indirect', 'Other indirect medical cause'), ('unknown_under_investigation', 'Unknown / under investigation'), ('other_specified', 'Other specified cause')], help_text='Specific structured cause for new records. Leave blank if no maternal death reported.', max_length=50, null=True, verbose_name='Maternal death specific cause'),
        ),
        migrations.AddField(
            model_name='mpdsr',
            name='maternal_death_timing',
            field=models.CharField(blank=True, choices=[('during_pregnancy', 'During pregnancy'), ('during_labor', 'During labor / childbirth'), ('within_24h_postpartum', 'Within 24 hours postpartum'), ('day_2_7_postpartum', '2–7 days postpartum'), ('day_8_42_postpartum', '8–42 days postpartum'), ('unknown', 'Unknown')], max_length=30, null=True, verbose_name='Timing of maternal death'),
        ),
    ]
