# Generated by Django 5.1.4 on 2026-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0113_mpdsr_maternal_death_cause_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpdsr',
            name='causeofmaternaldeaths_m',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Cause of maternal deaths'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='causeofneonataldeath_n',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Cause of neonatal death'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='interventionperformed',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Intervention performed'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='recfromMPDSRcommittee',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Recommendation from MPDSR committee'),
        ),
    ]
