# Generated by Django 5.1.4 on 2026-04-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0114_alter_mpdsr_causeofmaternaldeaths_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qicdataset',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qicdataset',
            name='qictotalquestions',
        ),
        migrations.RemoveField(
            model_name='qicdataset',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qiccommdate',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicfacility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpipupdatedvalue',
            field=models.IntegerField(default=0, verbose_name='8. Has the PIP been updated in last month QI committee’s meeting?'),
        ),
    ]
