# Generated by Django 5.1.4 on 2026-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0115_remove_qicdataset_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qicdataset',
            options={'ordering': ['-qiccommdate', 'qicfacility'], 'verbose_name': 'QIC', 'verbose_name_plural': 'QIC'},
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicaction_points_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicactions_completed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qiccommittee_members_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicdata_quality_issue_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicfollowup_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qichealthshurainvolvedincorract_bool',
            field=models.BooleanField(default=False, verbose_name='14. Has the HF Shura-e-Sihie been involved in the completion of the corrective actions in last month?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qichqiptollavail_bool',
            field=models.BooleanField(default=False, verbose_name='6. Is a copy of the Harmonized Quality Improvement Program (HQIP) tool available and accessible at the HF?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qiclastmonth_bool',
            field=models.BooleanField(default=False, verbose_name='2. Was the QI committee’s meeting conducted in last month?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmeeting_quorum_met',
            field=models.BooleanField(default=False, verbose_name='Was quorum met in the last QIC meeting?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmenteelogbookavial_bool',
            field=models.BooleanField(default=False, verbose_name='11. Is the mentee logbook available in the HF?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmenteelogbookupdated_bool',
            field=models.BooleanField(default=False, verbose_name='12. Has the mentee logbook been updated with the learning sessions conducted in last month and signed by the mentors of the HF?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmetwithhealthshura_bool',
            field=models.BooleanField(default=False, verbose_name='13. Has the QI committee met the HF Shura-e-Sihie in last month? Please refer to the related meeting minutes'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmmavial_bool',
            field=models.BooleanField(default=False, verbose_name='3. Are the meeting minutes of QI committee’s last month’s meeting available?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmmdatause_bool',
            field=models.BooleanField(default=False, verbose_name='5. Were data use discussed in the last month QI committee’s meeting? Please refer to the meeting minutes of last month'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicmmsigned_bool',
            field=models.BooleanField(default=False, verbose_name='4. Did the participants of the QI committee sign the meeting minutes of last month meeting?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicnext_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicngoinvolved_bool',
            field=models.BooleanField(default=False, verbose_name='9. Has the NGO been involved in the corrective actions completed in last month?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpeertopeeravail_bool',
            field=models.BooleanField(default=False, verbose_name='10. Have peer to peer learning sessions been conducted within the health facility during the last month?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpercentscore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpipavail_bool',
            field=models.BooleanField(default=False, verbose_name='7. Is a Performance Improvement Plan (PIP) available at the HF?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicpipupdated_bool',
            field=models.BooleanField(default=False, verbose_name='8. Has the PIP been updated in last month QI committee’s meeting?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qictoravail_bool',
            field=models.BooleanField(default=False, verbose_name='1. Are the Terms of Reference (TOR) of QI focal point and QI committee available at HF?'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qictotalquestions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='qicvalidated_by_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qichealthshurainvolvedincorractvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 14. Has the HF Shura-e-Sihie been involved in the completion of the corrective actions in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qichqiptollavailvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 6. Is a copy of the Harmonized Quality Improvement Program (HQIP) tool available and accessible at the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qiclastmonthvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 2. Was the QI committee’s meeting conducted in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmenteelogbookavialvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 11. Is the mentee logbook available in the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmenteelogbookupdatedvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 12. Has the mentee logbook been updated with the learning sessions conducted in last month and signed by the mentors of the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmetwithhealthshuravalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 13. Has the QI committee met the HF Shura-e-Sihie in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmmavialvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 3. Are the meeting minutes of QI committee’s last month’s meeting available.'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmmdatausevalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 5. Were data use discussed in the last month QI committee’s meeting?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicmmsignedvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 4. Did the participants of the QI committee sign the meeting minutes of last month meeting?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicngoinvolvedvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 9. Has the NGO been involved in the corrective actions completed in last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpeertopeeravailvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 10. Have peer to peer learning sessions been conducted within the health facility during the last month?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpipavailvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 7. Is a Performance Improvement Plan (PIP) available at the HF?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qicpipupdatedvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 8. Has the PIP been updated in last month QI committee’s meeting?'),
        ),
        migrations.AlterField(
            model_name='qicdataset',
            name='qictoravailvalue',
            field=models.IntegerField(default=0, verbose_name='Legacy - 1. Are the Terms of Reference (TOR) of QI focal point and QI committee available at HF?'),
        ),
    ]
