# Generated by Django 5.1.4 on 2026-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0116_alter_qicdataset_options_qicdataset_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qicdataset',
            name='qictotalquestions',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
