# Generated by Django 5.1.4 on 2026-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0117_alter_qicdataset_qictotalquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='qicdataset',
            name='monthqic',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=2, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='qicdataset',
            name='yearqic',
            field=models.IntegerField(choices=[(2026, '2026'), (2026, '2026'), (2027, '2027')], default=2027, verbose_name='Year'),
        ),
    ]
