# Generated by Django 5.1.4 on 2026-04-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0118_qicdataset_monthqic_qicdataset_yearqic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qicdataset',
            name='qiccommdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
