# Generated by Django 5.1.4 on 2026-04-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0119_alter_qicdataset_qiccommdate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='qicdataset',
            constraint=models.UniqueConstraint(fields=('qicfacility', 'yearqic', 'monthqic'), name='unique_qic_per_facility_month_year'),
        ),
    ]
