# Generated by Django 5.1.4 on 2026-04-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0119_alter_qicdataset_qiccommdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qicdataset',
            options={'ordering': ['-created_at', 'qicfacility'], 'verbose_name': 'QIC', 'verbose_name_plural': 'QIC'},
        ),
    ]
