# Generated by Django 5.1.4 on 2026-04-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0120_qicdataset_unique_qic_per_facility_month_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qicdataset',
            name='unique_qic_per_facility_month_year',
        ),
    ]
