# Generated by Django 5.1.4 on 2026-05-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Baseline / Progress')),
            ],
        ),
        migrations.CreateModel(
            name='GregorianMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Calendar Month')),
            ],
        ),
        migrations.CreateModel(
            name='GregorianYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True, verbose_name='Calendar Year')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Period')),
            ],
        ),
        migrations.CreateModel(
            name='ShamsiMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Afghanistan Month')),
            ],
        ),
        migrations.CreateModel(
            name='ShamsiYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True, verbose_name='Afghanistan Year')),
            ],
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='n_maternaldeathreported',
            field=models.IntegerField(default=0, verbose_name='Maternal Death reported'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='n_maternaldeathreviewed',
            field=models.IntegerField(default=0, verbose_name='Maternal Death reviewed'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='n_mpdsrcommittee',
            field=models.IntegerField(default=0, verbose_name='Staff participated'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='nastillbirthreportedreported',
            field=models.IntegerField(default=0, verbose_name='Antepartum Still birth reported'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='nastillbirthreportedreviewed',
            field=models.IntegerField(default=0, verbose_name='Antepartum Still birth reviewed'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='nistillbirthreported',
            field=models.IntegerField(default=0, verbose_name='Intrapartum Still birth reported'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='nistillbirthreviewed',
            field=models.IntegerField(default=0, verbose_name='Intrapartum Still birth reviewed'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='nndeath_afteralivebirth_reported',
            field=models.IntegerField(default=0, verbose_name='Neonatal Death after a live birth reported'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='nndeath_afteralivebirth_reviewed',
            field=models.IntegerField(default=0, verbose_name='Neonatal Death after a live birth reviewed'),
        ),
        migrations.AlterField(
            model_name='mpdsr',
            name='recfromMPDSRcommittee',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Committee Recommendation'),
        ),
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='files_selected',
            field=models.PositiveIntegerField(default=0, help_text='Expected range: 0–20.', verbose_name='Out of total deliveries in the month, select RANDOMLY up to 20 patient files and record number of files selected'),
        ),
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Deliveries'),
        ),
    ]
