# Generated by Django 5.1.4 on 2026-04-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0121_remove_qicdataset_unique_qic_per_facility_month_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qicdataset',
            options={'ordering': ['-created_at', 'qicfacility'], 'verbose_name': 'QIC', 'verbose_name_plural': 'QIC'},
        ),
    ]
