# Generated by Django 5.1.4 on 2026-05-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0121_baselineprogress_gregorianmonth_gregorianyear_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whochildbirthchecklistmonthly',
            name='bl_progress_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.baselineprogress', verbose_name='Baseline and Progress'),
        ),
        migrations.AddField(
            model_name='whochildbirthchecklistmonthly',
            name='gre_month_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.gregorianmonth', verbose_name='Calendar Month'),
        ),
        migrations.AddField(
            model_name='whochildbirthchecklistmonthly',
            name='gre_year_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.gregorianyear', verbose_name='Calendar Year'),
        ),
        migrations.AddField(
            model_name='whochildbirthchecklistmonthly',
            name='period_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.period', verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='whochildbirthchecklistmonthly',
            name='shamsi_month_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.shamsimonth', verbose_name='Afghanistan Month'),
        ),
        migrations.AddField(
            model_name='whochildbirthchecklistmonthly',
            name='shamsi_year_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.shamsiyear', verbose_name='Afghanistan Year'),
        ),
    ]
