# Generated by Django 5.1.4 on 2026-05-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0122_whochildbirthchecklistmonthly_bl_progress_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='files_selected',
            field=models.PositiveIntegerField(default=0, help_text='Expected range: 0–20.', verbose_name='Out of total deliveries in this month, select RANDOMLY up to 20 patient files and record number of files selected'),
        ),
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='gre_month',
            field=models.CharField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='gre_year',
            field=models.CharField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='shamsi_month',
            field=models.CharField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='shamsi_year',
            field=models.CharField(verbose_name='Year'),
        ),
    ]
