# Generated by Django 5.1.4 on 2026-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0123_alter_whochildbirthchecklistmonthly_files_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whochildbirthchecklistmonthly',
            name='afiat_flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='AFIAT'),
        ),
    ]
