# Generated by Django 5.1.4 on 2026-08-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0124_alter_whochildbirthchecklistmonthly_afiat_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimPPHDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'AIM-PPH DASHBOARD',
                'verbose_name_plural': 'AIM-PPH DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.aimpph',),
        ),
    ]
