# Generated by Django 5.1.4 on 2026-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0125_aimpphdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQIPAssessmentDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'HQIP DASHBOARD',
                'verbose_name_plural': 'HQIP DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.hqipassessmentheader',),
        ),
    ]
