# Generated by Django 5.1.4 on 2026-08-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0126_hqipassessmentdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQIPContentDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'HQIP ANALYSIS DASHBOARD',
                'verbose_name_plural': 'HQIP ANALYSIS DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.hqipassessmentheader',),
        ),
    ]
