# Generated by Django 5.1.4 on 2026-08-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0127_hqipcontentdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baselineprogress',
            options={'verbose_name': 'BASELINE PROGRESS', 'verbose_name_plural': 'BASELINE PROGRESS'},
        ),
        migrations.AlterModelOptions(
            name='gregorianmonth',
            options={'verbose_name': 'GREGORIAN MONTHS', 'verbose_name_plural': 'GREGORIAN MONTHS'},
        ),
        migrations.AlterModelOptions(
            name='gregorianyear',
            options={'verbose_name': 'GREGORIAN YEARS', 'verbose_name_plural': 'GREGORIAN YEARS'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'PERIOD', 'verbose_name_plural': 'PERIOD'},
        ),
        migrations.AlterModelOptions(
            name='shamsimonth',
            options={'verbose_name': 'SHAMSI MONTH', 'verbose_name_plural': 'SHAMRI MONTH'},
        ),
        migrations.AlterModelOptions(
            name='shamsiyear',
            options={'verbose_name': 'SHAMSI YEAR', 'verbose_name_plural': 'SHAMRI YEAR'},
        ),
        migrations.AlterField(
            model_name='baselineprogress',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gregorianmonth',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gregorianyear',
            name='year',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shamsimonth',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shamsiyear',
            name='year',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
