# Generated by Django 5.1.4 on 2026-09-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0128_alter_baselineprogress_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimPEEDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'AIM-PEE DASHBOARD',
                'verbose_name_plural': 'AIM-PEE DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.aimpee',),
        ),
    ]
