# Generated by Django 5.1.4 on 2026-09-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0129_aimpeedashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeSurgeryDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'SAFE SURGERY DASHBOARD',
                'verbose_name_plural': 'SAFE SURGERY DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.safesurgeryclinical',),
        ),
    ]
