# Generated by Django 5.1.4 on 2026-09-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0130_safesurgerydashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoChildbirthChecklistDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'WHO CHILDBIRTH CHECKLIST DASHBOARD',
                'verbose_name_plural': 'WHO CHILDBIRTH CHECKLIST DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.whochildbirthchecklistmonthly',),
        ),
    ]
