# Generated by Django 5.1.4 on 2026-09-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0131_whochildbirthchecklistdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='pph_cs_num',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Number of Post-Partum Hemorrhage cases during or after CS =>1000ml'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='pph_cs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage (%)', max_digits=5, null=True, verbose_name='Cesarean PPH Rate (=>1000 ml) (%)'),
        ),
        migrations.AlterField(
            model_name='safesurgeryclinical',
            name='total_deliv',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Total Number of Deliveries (Normal + C-section + Assisted)'),
        ),
    ]
