# Generated by Django 5.1.4 on 2026-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0132_alter_safesurgeryclinical_pph_cs_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimpee',
            name='preeclampsia_diagnosed',
            field=models.BigIntegerField(default=0, verbose_name='3. Number of ANC women diagnosed with Mild Pre-Eclampsia (BP >140/90 + proteinuria)'),
        ),
    ]
