# Generated by Django 5.1.4 on 2026-10-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0133_alter_aimpee_preeclampsia_diagnosed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPDSRDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'MPDSR Dashboard',
                'verbose_name_plural': 'MPDSR Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hiva.mpdsr',),
        ),
    ]
