# Generated by Django 5.1.4 on 2026-01-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiva', '0096_add_assessor_continuetophase2_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Position')),
            ],
            options={
                'verbose_name': 'STAFF PROFESSION',
                'verbose_name_plural': 'STAFF PROFESSION',
            },
        ),
        migrations.CreateModel(
            name='ThematicMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'MENTORSHIP THEMATIC AREA',
                'verbose_name_plural': 'MENTORSHIP THEMATIC AREA',
            },
        ),
        migrations.CreateModel(
            name='Mentorshipvisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField()),
                ('visitround', models.IntegerField(blank=True, null=True)),
                ('mentorshipstarttime', models.TimeField()),
                ('mentorshipendtime', models.TimeField()),
                ('facilityfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
            ],
            options={
                'verbose_name': 'MENTORSHIP VISIT',
                'verbose_name_plural': 'MENTORSHIP VISIT',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField()),
                ('lastname', models.CharField(blank=True, null=True)),
                ('tazkiranumber', models.CharField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, choices=[(True, 'Female'), (False, 'Male')], default=True, null=True, verbose_name='Gender')),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=True, null=True, verbose_name='Status')),
                ('hfname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.position')),
            ],
            options={
                'verbose_name': 'MENTEE',
                'verbose_name_plural': 'MENTEE',
            },
        ),
        migrations.CreateModel(
            name='MentorshipTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(blank=True, null=True)),
                ('name', models.TextField()),
                ('namedari', models.TextField(blank=True, null=True)),
                ('namepashto', models.TextField(blank=True, null=True)),
                ('nameeng', models.TextField(blank=True, null=True)),
                ('thematicfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.thematicmentorship')),
            ],
            options={
                'verbose_name': 'MENTORSHIP TOPIC',
                'verbose_name_plural': 'MENTORSHIP TOPIC',
            },
        ),
        migrations.CreateModel(
            name='Mentorshipdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.BooleanField(verbose_name='Learning Session')),
                ('pc', models.BooleanField(verbose_name='Patient Competent')),
                ('mc', models.BooleanField(verbose_name='Model Compotent')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hiva.assessor', verbose_name='Mentor')),
                ('topicname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiptopics', verbose_name='Topic')),
                ('mentorshipvistfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mentorship.mentorshipvisit')),
                ('menteename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.staff', verbose_name='Mentee')),
                ('thematicname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.thematicmentorship', verbose_name='Mentorship Thematic Area')),
            ],
            options={
                'verbose_name': 'MENTORSHIP DETAIL',
                'verbose_name_plural': 'MENTORSHIP DETAIL',
            },
        ),
    ]
