# Generated by Django 5.1.4 on 2026-01-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0097_position'),
        ('mentorship', '0001_initial'),
        ('survey', '0008_alter_patientsafetyheader_staff_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.position'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
