# Generated by Django 5.1.4 on 2026-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_staff_position_delete_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicmentorship',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='ls',
            field=models.BooleanField(default=False, verbose_name='Learning Session'),
        ),
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='mc',
            field=models.BooleanField(default=False, verbose_name='Model Competent'),
        ),
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='pc',
            field=models.BooleanField(default=False, verbose_name='Patient Competent'),
        ),
        migrations.AlterField(
            model_name='mentorshiptopics',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tazkiranumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thematicmentorship',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
