# Generated by Django 5.1.4 on 2026-01-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0102_alter_mpdsr_options_mpdsr_created_at_and_more'),
        ('mentorship', '0003_thematicmentorship_shortname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipdetails',
            name='topicname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiptopics', verbose_name='Topic code'),
        ),
        migrations.AlterField(
            model_name='mentorshiptopics',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Topic code'),
        ),
        migrations.AlterField(
            model_name='mentorshiptopics',
            name='thematicfk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.thematicmentorship', verbose_name='Mentorship Thematic Area'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='facilityfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='mentorshipendtime',
            field=models.TimeField(verbose_name='Mentorship End Time'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='mentorshipstarttime',
            field=models.TimeField(verbose_name='Mentorship Start Time'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='visitdate',
            field=models.DateField(verbose_name='Visit Date'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='visitround',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visit Round'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hfname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tazkiranumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tazkira Number'),
        ),
        migrations.AlterField(
            model_name='thematicmentorship',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mentorship Thematic Area'),
        ),
    ]
