# Generated by Django 5.1.4 on 2026-01-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_alter_mentorshipdetails_topicname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tazkiranumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tazkira Number'),
        ),
    ]
