# Generated by Django 5.1.4 on 2026-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_alter_staff_tazkiranumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fathername',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Father Name'),
        ),
    ]
