# Generated by Django 5.1.4 on 2026-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_staff_fathername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorshiptopics',
            options={'ordering': ['track', 'seq_no'], 'verbose_name': 'MENTORSHIP TOPIC', 'verbose_name_plural': 'MENTORSHIP TOPIC'},
        ),
        migrations.AddField(
            model_name='mentorshiptopics',
            name='seq_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorshiptopics',
            name='track',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
