# Generated by Django 5.1.4 on 2026-02-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_alter_mentorshiptopics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeTopicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPETENT', 'Competent')], default='NOT_STARTED', max_length=20)),
                ('consecutive_ls', models.PositiveSmallIntegerField(default=0)),
                ('last_session_type', models.CharField(blank=True, default='', max_length=2)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('competent_date', models.DateField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.staff')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshiptopics')),
            ],
            options={
                'unique_together': {('mentee', 'topic')},
            },
        ),
    ]
