# Generated by Django 5.1.4 on 2026-02-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0109_aimpph_pph_medication_uterotonic_aimpph_pph_total_and_more'),
        ('mentorship', '0008_menteetopicstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicmentorship',
            name='hqip_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentorship_thematics', to='hiva.area', verbose_name='Mapped HQIP Thematic Area'),
        ),
    ]
