# Generated by Django 5.1.4 on 2026-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0009_thematicmentorship_hqip_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='mentorshipendtime',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='mentorshipvisit',
            name='mentorshipstarttime',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
