# Generated by Django 5.1.4 on 2026-07-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0010_alter_mentorshipvisit_mentorshipendtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Mentorship Dashboard',
                'verbose_name_plural': 'Mentorship Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mentorship.mentorshipvisit',),
        ),
    ]
