# Generated by Django 5.1.4 on 2026-08-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0011_mentorshipdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorshipdashboard',
            options={'verbose_name': 'MENTORSHIP DASHBOARD', 'verbose_name_plural': 'MENTORSHIP DASHBOARD'},
        ),
    ]
