# Generated by Django 6.0 on 2025-12-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmsDashboardDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'KMS Dashboard',
                'verbose_name_plural': 'KMS Dashboard',
                'managed': False,
            },
        ),
    ]
