# Generated by Django 6.0 on 2025-12-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0002_kmsdashboarddummy'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMSTag',
            fields=[
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
    ]
