# Generated by Django 5.1.4 on 2026-01-21 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMISRawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='hmis/raw/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('hf_count', models.IntegerField(default=0)),
                ('period_min', models.CharField(blank=True, default='', max_length=6)),
                ('period_max', models.CharField(blank=True, default='', max_length=6)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HMISFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(blank=True, default='', max_length=255)),
                ('dist', models.CharField(blank=True, default='', max_length=255)),
                ('hf', models.CharField(db_index=True, max_length=255)),
                ('periodcode', models.CharField(db_index=True, max_length=6)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('month_name', models.CharField(blank=True, default='', max_length=20)),
                ('hf_name_cleaned', models.CharField(blank=True, default='', max_length=255)),
                ('hfid', models.IntegerField(db_index=True, default=0)),
                ('hiva_hfs', models.BooleanField(db_index=True, default=False)),
                ('indicator_code', models.CharField(db_index=True, max_length=128)),
                ('indicator_name', models.CharField(max_length=512)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='hmis.hmisrawupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hf', 'periodcode', 'indicator_code'), name='uniq_hmis_hf_period_indicator')],
            },
        ),
    ]
