# Generated by Django 5.1.4 on 2026-01-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmisfact',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='HMISMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(blank=True, default='', max_length=255)),
                ('dist', models.CharField(blank=True, default='', max_length=255)),
                ('hf', models.CharField(db_index=True, max_length=255)),
                ('periodcode', models.CharField(db_index=True, max_length=6)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('month_name', models.CharField(blank=True, default='', max_length=20)),
                ('hfid', models.IntegerField(db_index=True, default=0)),
                ('hiva_hfs', models.BooleanField(db_index=True, default=False)),
                ('anc1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('anc2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('anc3', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('anc4', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('pnc1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('pnc2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('n_delivery', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('a_delivery', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('c_section', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('lbw', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('stillbirth', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='hmis.hmisrawupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hf', 'periodcode'), name='uniq_hmis_summary_hf_period')],
            },
        ),
    ]
