# Generated by Django 5.1.4 on 2026-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0002_alter_hmisfact_value_hmismonthlysummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmisfact',
            options={'verbose_name': 'FACILITY REPORT', 'verbose_name_plural': 'FACILITY REPORT'},
        ),
        migrations.AlterModelOptions(
            name='hmismonthlysummary',
            options={'verbose_name': 'FACILITY MONTHLY SUMMARY', 'verbose_name_plural': 'FACILITY MONTHLY SUMMARY'},
        ),
        migrations.AlterModelOptions(
            name='hmisrawupload',
            options={'verbose_name': 'FACILITY DATA DUMP', 'verbose_name_plural': 'FACILITY DATA DUMP'},
        ),
        migrations.AlterField(
            model_name='hmisfact',
            name='dist',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='hmisfact',
            name='hf',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Health Facility'),
        ),
        migrations.AlterField(
            model_name='hmisfact',
            name='hiva_hfs',
            field=models.BooleanField(db_index=True, default=False, verbose_name='HIVA HF'),
        ),
        migrations.AlterField(
            model_name='hmisfact',
            name='prov',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='a_delivery',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='anc1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='anc2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='anc3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='anc4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='c_section',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='lbw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='n_delivery',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='pnc1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='pnc2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmismonthlysummary',
            name='stillbirth',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='hmisrawupload',
            name='file',
            field=models.FileField(upload_to='hmis/raw/', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='hmisrawupload',
            name='hf_count',
            field=models.IntegerField(default=0, verbose_name='Health Facility Count'),
        ),
        migrations.AlterField(
            model_name='hmisrawupload',
            name='period_max',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='End Month'),
        ),
        migrations.AlterField(
            model_name='hmisrawupload',
            name='period_min',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Start Month'),
        ),
        migrations.AlterField(
            model_name='hmisrawupload',
            name='row_count',
            field=models.IntegerField(default=0, verbose_name='Rows Count'),
        ),
        migrations.AlterField(
            model_name='hmisrawupload',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Spread sheet Name'),
        ),
    ]
