# Generated by Django 5.1.4 on 2026-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0003_alter_hmisfact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(max_length=100)),
                ('indicator_name', models.CharField(max_length=255)),
                ('indicator_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('indicator_group', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_description', models.TextField(blank=True, null=True)),
                ('numerator_definition', models.TextField(blank=True, null=True)),
                ('denominator_definition', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_level', models.CharField(blank=True, max_length=100, null=True)),
                ('data_source', models.CharField(default='HMIS', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hmis_indicator_metadata',
                'ordering': ['sort_order', 'indicator_name'],
                'unique_together': {('indicator_code', 'indicator_name')},
            },
        ),
    ]
