# Generated by Django 5.1.4 on 2026-08-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0004_indicatormetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMISDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'HMIS DASHBOARD',
                'verbose_name_plural': 'HMIS DASHBOARD',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hmis.hmismonthlysummary',),
        ),
    ]
