# Generated by Django 5.1.4 on 2026-08-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmis', '0005_hmisdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatormetadata',
            options={'ordering': ['sort_order', 'indicator_name'], 'verbose_name': 'INDICATOR METADATA', 'verbose_name_plural': 'INDICATOR METADATA'},
        ),
    ]
