# Generated by Django 5.1.4 on 2026-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='baseline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
