# Generated by Django 5.1.4 on 2026-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_indicator_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='area',
            field=models.TextField(blank=True, null=True, verbose_name='Thematic Area'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.TextField(verbose_name='Indicator'),
        ),
    ]
