# Generated by Django 5.1.4 on 2026-08-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_indicator_area_alter_indicator_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'PERFORMANCE INDICATOR', 'verbose_name_plural': 'PERFORMANCE INDICATOR'},
        ),
        migrations.AlterModelOptions(
            name='indicatorreport',
            options={'verbose_name': 'INDICATOR TRACKING', 'verbose_name_plural': 'INDICATOR TRACKING'},
        ),
    ]
