# Generated by Django 5.1.4 on 2026-04-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Skill Lab')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PLANNED', 'Planned'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20, verbose_name='Skill Lab Status')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_labs', to='hiva.facility', verbose_name='Facility')),
                ('implementing_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skilllabs', to='hiva.implementor', verbose_name='Implementing Partner')),
            ],
            options={
                'verbose_name': 'Skill Lab',
                'verbose_name_plural': 'Skill Labs',
                'ordering': ['facility__name', 'name'],
                'unique_together': {('facility', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SkillLabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(help_text='Unique source/import record ID', max_length=100, unique=True, verbose_name='Record ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('month_name', models.CharField(blank=True, max_length=20, null=True)),
                ('month_year', models.CharField(blank=True, max_length=30, null=True)),
                ('lab_round', models.PositiveIntegerField(verbose_name='Lab Round')),
                ('session_date', models.DateField(verbose_name='Date')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Check In')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check Out')),
                ('session_type', models.CharField(choices=[('LS', 'Learning Session'), ('MC', 'Mentoring/Coaching'), ('PC', 'Practice/Coaching'), ('OTHER', 'Other')], max_length=20, verbose_name='Session Type')),
                ('helper1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Helper 1')),
                ('mentor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mentor')),
                ('ce_checklist_applied', models.BooleanField(default=False, verbose_name='CE Checklist Applied')),
                ('planned_session', models.BooleanField(default=False)),
                ('completed_session', models.BooleanField(default=True)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('action_points', models.TextField(blank=True, null=True)),
                ('followup_needed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skilllab_sessions', to='hiva.implementor', verbose_name='Mentor Organization')),
                ('skill_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='skill_lab.skilllab')),
            ],
            options={
                'verbose_name': 'Skill Lab Session',
                'verbose_name_plural': 'Skill Lab Sessions',
                'ordering': ['-session_date', 'skill_lab__name'],
            },
        ),
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mentorship Thematic Area')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('hqip_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill_lab_thematics', to='hiva.area', verbose_name='Mapped HQIP Thematic Area')),
            ],
            options={
                'verbose_name': 'MENTORSHIP THEMATIC AREA',
                'verbose_name_plural': 'MENTORSHIP THEMATIC AREA',
            },
        ),
        migrations.CreateModel(
            name='SkillLabTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Topic code')),
                ('namedari', models.TextField(blank=True, null=True)),
                ('namepashto', models.TextField(blank=True, null=True)),
                ('nameeng', models.TextField(blank=True, null=True)),
                ('track', models.CharField(blank=True, default='', max_length=20)),
                ('seq_no', models.PositiveSmallIntegerField(default=0)),
                ('thematicfk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill_lab.thematicarea', verbose_name='Mentorship Thematic Area')),
            ],
            options={
                'verbose_name': 'MENTORSHIP TOPIC',
                'verbose_name_plural': 'MENTORSHIP TOPIC',
                'ordering': ['track', 'seq_no'],
            },
        ),
        migrations.CreateModel(
            name='SkillLabParticipantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(max_length=255, verbose_name='Mentee Name')),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='UNKNOWN', max_length=10)),
                ('ls', models.BooleanField(default=False, verbose_name='LS')),
                ('mc', models.BooleanField(default=False, verbose_name='MC')),
                ('attended', models.BooleanField(default=True)),
                ('competency_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPETENT', 'Competent'), ('NEEDS_REPEAT', 'Needs Repeat')], default='IN_PROGRESS', max_length=30)),
                ('pre_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('post_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('demonstration_done', models.BooleanField(default=False)),
                ('return_demonstration_done', models.BooleanField(default=False)),
                ('checklist_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_given', models.BooleanField(default=False)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('mentee_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skilllab_mentee_records', to='hiva.facility', verbose_name='Mentee Facility')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skilllab_participant_records', to='hiva.position', verbose_name='Profession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='skill_lab.skilllabsession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_records', to='skill_lab.skilllabtopic')),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_records', to='skill_lab.thematicarea')),
            ],
            options={
                'verbose_name': 'Skill Lab Participant Record',
                'verbose_name_plural': 'Skill Lab Participant Records',
                'ordering': ['session__session_date', 'mentee_name'],
            },
        ),
        migrations.AddIndex(
            model_name='skilllabsession',
            index=models.Index(fields=['session_date'], name='skill_lab_s_session_bbdd82_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabsession',
            index=models.Index(fields=['year', 'month'], name='skill_lab_s_year_90b157_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabsession',
            index=models.Index(fields=['lab_round'], name='skill_lab_s_lab_rou_b6ec84_idx'),
        ),
        migrations.AddIndex(
            model_name='skilllabparticipantrecord',
            index=models.Index(fields=['mentee_name'], name='skill_lab_s_mentee__500a62_idx'),
        ),
        migrations.AddConstraint(
            model_name='skilllabparticipantrecord',
            constraint=models.UniqueConstraint(fields=('session', 'mentee_name', 'topic'), name='unique_skilllab_session_mentee_topic'),
        ),
    ]
