# Generated by Django 5.1.4 on 2026-04-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
        ('skill_lab', '0002_copy_mentorship_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Lab_Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('fathername', models.CharField(blank=True, max_length=200, null=True, verbose_name='Father Name')),
                ('tazkiranumber', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tazkira Number')),
                ('gender', models.BooleanField(blank=True, choices=[(True, 'Female'), (False, 'Male')], default=True, null=True, verbose_name='Gender')),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Inactive')], default=True, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'MENTEE',
                'verbose_name_plural': 'MENTEE',
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.AlterModelOptions(
            name='skilllabtopic',
            options={'ordering': ['track', 'seq_no', 'name'], 'verbose_name': 'MENTORSHIP TOPIC', 'verbose_name_plural': 'MENTORSHIP TOPIC'},
        ),
        migrations.AlterModelOptions(
            name='thematicarea',
            options={'ordering': ['name'], 'verbose_name': 'MENTORSHIP THEMATIC AREA', 'verbose_name_plural': 'MENTORSHIP THEMATIC AREA'},
        ),
        migrations.RemoveIndex(
            model_name='skilllabparticipantrecord',
            name='skill_lab_s_mentee__500a62_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilllabsession',
            name='skill_lab_s_year_90b157_idx',
        ),
        migrations.RemoveField(
            model_name='skilllabsession',
            name='helper1',
        ),
        migrations.RemoveField(
            model_name='skilllabsession',
            name='month',
        ),
        migrations.RemoveField(
            model_name='skilllabsession',
            name='month_name',
        ),
        migrations.RemoveField(
            model_name='skilllabsession',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='skilllabsession',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='skilllabsession',
            name='year',
        ),
        migrations.AlterField(
            model_name='skilllabparticipantrecord',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='FEMALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='skilllabsession',
            name='check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='skilllabsession',
            name='check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Check Out'),
        ),
        migrations.AlterField(
            model_name='skilllabtopic',
            name='thematicfk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='skill_lab.thematicarea', verbose_name='Mentorship Thematic Area'),
        ),
        migrations.AddConstraint(
            model_name='skilllabtopic',
            constraint=models.UniqueConstraint(fields=('thematicfk', 'name'), name='unique_skilllabtopic_thematic_name'),
        ),
        migrations.AddField(
            model_name='skill_lab_mentee',
            name='hfname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.facility', verbose_name='Health Facility'),
        ),
        migrations.AddField(
            model_name='skill_lab_mentee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiva.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='skilllabparticipantrecord',
            name='mentee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_lab_records', to='skill_lab.skill_lab_mentee', verbose_name='Mentee Name'),
        ),
    ]
