# Generated by Django 5.1.4 on 2026-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_lab', '0003_skill_lab_mentee_alter_skilllabtopic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllabparticipantrecord',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='skilllabparticipantrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='skilllabparticipantrecord',
            name='mentee_facility',
        ),
    ]
