# Generated by Django 5.1.4 on 2026-04-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
        ('skill_lab', '0004_remove_skilllabparticipantrecord_attended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilllab',
            options={'ordering': ['facility__name', 'name'], 'verbose_name': 'MNH SKILL LAB', 'verbose_name_plural': 'MNH SKILL LAB'},
        ),
        migrations.AlterModelOptions(
            name='skilllabparticipantrecord',
            options={'ordering': ['session__session_date', 'mentee_name'], 'verbose_name': 'MNH SKILL LAB RECORD', 'verbose_name_plural': 'MNH SKILL LAB RECORD'},
        ),
        migrations.AlterModelOptions(
            name='skilllabsession',
            options={'ordering': ['-session_date', 'skill_lab__name'], 'verbose_name': 'MNH SKILL LAB SESSION', 'verbose_name_plural': 'MNH SKILL LAB SESSION'},
        ),
        migrations.AlterUniqueTogether(
            name='skilllab',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='skilllab',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skilllabs', to='hiva.implementor', verbose_name='Mentor Organization'),
        ),
        migrations.AlterField(
            model_name='skilllab',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Skill Lab Name'),
        ),
    ]
