# Generated by Django 5.1.4 on 2026-04-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
        ('skill_lab', '0006_copy_staff_to_skilllab_mentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabsession',
            name='mentor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skilllab_sessions', to='hiva.assessor', verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='skilllabsession',
            name='session_type',
            field=models.CharField(choices=[('Group', 'Group'), ('Individual', 'Individual')], max_length=20, verbose_name='Session Type'),
        ),
    ]
