# Generated by Django 5.1.4 on 2026-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_lab', '0007_alter_skilllabsession_mentor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllabsession',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mentor'),
        ),
    ]
