# Generated by Django 5.1.4 on 2026-04-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_lab', '0009_alter_skilllabsession_mentor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllabparticipantrecord',
            name='profession',
        ),
    ]
