# Generated by Django 5.1.4 on 2026-07-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_lab', '0010_remove_skilllabparticipantrecord_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLabDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Skill Lab Dashboard',
                'verbose_name_plural': 'Skill Lab Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('skill_lab.skilllabsession',),
        ),
    ]
