# Generated by Django 5.1.4 on 2026-08-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_lab', '0011_skilllabdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilllabdashboard',
            options={'verbose_name': 'SKILL LAB DASHBOARD', 'verbose_name_plural': 'SKILL LAB DASHBOARD'},
        ),
    ]
