# Generated by Django 5.1.4 on 2025-12-18 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiva', '0077_alter_assessor_options_alter_criteria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Work Area',
                'verbose_name_plural': 'Work Areas',
            },
        ),
        migrations.CreateModel(
            name='PatientSafetyHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveymonth', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')])),
                ('surveyyear', models.IntegerField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientsafety_assessments', to='hiva.assessor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientsafety_headers', to='hiva.facility')),
                ('staff_profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientsafety_professions', to='hiva.position')),
            ],
            options={
                'verbose_name': 'Patient Safety Survey Header',
                'verbose_name_plural': 'Patient Safety Survey Headers',
            },
        ),
        migrations.CreateModel(
            name='PatientSafetyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='1.In this unit, we work together as an effective team')),
                ('a2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='2.In this unit, we have enough staff to handle the workload')),
                ('a3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='3.Staff in this unit work longer hours than is best for patient care')),
                ('a4', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='4.This unit regularly reviews work processes to determine if changes are needed to improve patient safety')),
                ('a5', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='5.This unit relies too much on temporary, float, or PRN staff')),
                ('a6', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='6.In this unit, staff feel like their mistakes are held against them')),
                ('a7', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='7. When an event is reported in this unit, it feels like the person is being written up, not the problem')),
                ('a8', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='8.During busy times, staff in this unit help each other')),
                ('a9', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='9.There is a problem with disrespectful behavior by those working in this unit')),
                ('a10', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='10.When staff make errors, this unit focuses on learning rather than blaming individuals')),
                ('a11', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='11.The work pace in this unit is so rushed that it negatively affects patient safety')),
                ('a12', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='12.In this unit, changes to improve patient safety are evaluated to see how well they worked')),
                ('a13', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='13.In this unit, there is a lack of support for staff involved in patient safety errors ')),
                ('a14', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='14.This unit lets the same patient safety problems keep happening ')),
                ('b1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='1.My supervisor, manager, or clinical leader seriously considers staff suggestions for improving patient safety')),
                ('b2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='2.My supervisor, manager, or clinical leader wants us to work faster during busy times, even if it means taking shortcuts ')),
                ('b3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='3.My supervisor, manager, or clinical leader takes action to address patient safety concerns that are brought to their attention ')),
                ('c1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='1.We are informed about errors that happen in this unit')),
                ('c2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='2.When errors happen in this unit, we discuss ways to prevent them from happening again')),
                ('c3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='3.In this unit, we are informed about changes that are made based on event reports ')),
                ('c4', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='4.In this unit, staff speak up if they see something that may negatively affect patient care')),
                ('c5', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='5.When staff in this unit see someone with more authority doing something unsafe for patients, they speak up')),
                ('c6', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='6.When staff in this unit speak up, those with more authority are open to their patient safety concerns')),
                ('c7', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='7.In this unit, staff are afraid to ask questions when something does not seem right')),
                ('d1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='1.When a mistake is caught and corrected before reaching the patient, how often is this reported?')),
                ('d2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='2.When a mistake reaches the patient and could have harmed the patient, but did not, how often is this reported?')),
                ('d3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None'), (2, '1 to 2'), (3, '3 to 5'), (4, '6 to 10'), (5, '11 or more')], null=True, verbose_name='3.In the past 12 months, how many patient safety events have you reported?')),
                ('e1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True, verbose_name='1.How would you rate your unit/work area on patient safety?')),
                ('f1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='1.The actions of hospital management show that patient safety is a top priority')),
                ('f2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='2.Hospital management provides adequate resources to improve patient safety')),
                ('f3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='3.Hospital management seems interested in patient safety only after an adverse event happens')),
                ('f4', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='4.When transferring patients from one unit to another, important information is often left out')),
                ('f5', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='5.During shift changes, important patient care information is often left out')),
                ('f6', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Dose Not Apply or Don't Know")], null=True, verbose_name='6.During shift changes, there is adequate time to exchange all key patient care information')),
                ('g1', models.CharField(blank=True, choices=[('1', 'Less than 1 year'), ('2', '1 to 5 years'), ('3', '6 to 10 years'), ('4', '11 or more years')], max_length=1, null=True, verbose_name='1.How long have you worked in this hospital?')),
                ('g2', models.CharField(blank=True, choices=[('1', 'Less than 1 year'), ('2', '1 to 5 years'), ('3', '6 to 10 years'), ('4', '11 or more years')], max_length=1, null=True, verbose_name='2.In this hospital, how long have you worked in your current unit/work area?')),
                ('g3', models.CharField(blank=True, choices=[('1', 'Less than 30 hours per week'), ('2', '30 to 40 hours per week'), ('3', 'More than 40 hours per week')], max_length=1, null=True, verbose_name='3.Typically, how many hours per week do you work in this hospital?')),
                ('g4', models.CharField(blank=True, choices=[('1', 'YES, I typically have direct interaction or contact with patients'), ('2', 'NO, I typically do NOT have direct interaction or contact with patients')], max_length=1, null=True, verbose_name='4.In your staff position, do you typically have direct interaction or contact with patients?')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Your Comments: Please feel free to provide any comments about how things are done or could be done in your hospital that might affect patient safety.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patientsafety_details_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patientsafety_details_updated', to=settings.AUTH_USER_MODEL)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='survey.patientsafetyheader')),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patientsafety_details', to='survey.workarea')),
            ],
            options={
                'verbose_name': 'Patient Safety Survey Details',
                'verbose_name_plural': 'Patient Safety Survey Details',
            },
        ),
    ]
