# Generated by Django 5.1.4 on 2025-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsafetyheader',
            name='key_intervention_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetyheader',
            name='surveyyear',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027')]),
        ),
    ]
