# Generated by Django 5.1.4 on 2025-12-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_patientsafetyheader_key_intervention_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsafetyheader',
            options={'verbose_name': 'Patient Safety Culture', 'verbose_name_plural': 'Patient Safety Culture'},
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='1. In this unit, we work together as an effective team'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='10. When staff make errors, this unit focuses on learning rather than blaming individuals'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='11. The work pace in this unit is so rushed that it negatively affects patient safety'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='12. In this unit, changes to improve patient safety are evaluated to see how well they worked'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='13. In this unit, there is a lack of support for staff involved in patient safety errors'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='14. This unit lets the same patient safety problems keep happening'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='2. In this unit, we have enough staff to handle the workload'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='3. Staff in this unit work longer hours than is best for patient care'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='4. This unit regularly reviews work processes to determine if changes are needed to improve patient safety'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='5. This unit relies too much on temporary, float, or PRN staff'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='6. In this unit, staff feel like their mistakes are held against them'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='7. When an event is reported in this unit, it feels like the person is being written up, not the problem'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='8. During busy times, staff in this unit help each other'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a9',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='9. There is a problem with disrespectful behavior by those working in this unit'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='b1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='1. My supervisor/manager seriously considers staff suggestions for improving patient safety'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='b2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='2. My supervisor/manager wants us to work faster during busy times, even if it means taking shortcuts'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='b3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='3. My supervisor/manager takes action to address patient safety concerns that are brought to their attention'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='1. We are informed about errors that happen in this unit'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='2. When errors happen in this unit, we discuss ways to prevent them from happening again'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='3. In this unit, we are informed about changes made based on event reports'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='4. In this unit, staff speak up if they see something that may negatively affect patient care'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='5. When staff see someone with more authority doing something unsafe, they speak up'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='6. When staff speak up, those with more authority are open to patient safety concerns'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='7. Staff are afraid to ask questions when something does not seem right'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Your Comments: Please provide any comments about how things are done or could be done that might affect patient safety.'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='d1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='1. When a mistake is caught and corrected before reaching the patient, how often is this reported?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='d2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='2. When a mistake reaches the patient and could have harmed but did not, how often is this reported?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='d3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None'), (2, '1 to 2'), (3, '3 to 5'), (4, '6 to 10'), (5, '11 or more years')], null=True, verbose_name='3. In the past 12 months, how many patient safety events have you reported?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='e1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True, verbose_name='1. How would you rate your unit/work area on patient safety?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='1. Hospital management shows that patient safety is a top priority'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='2. Hospital management provides adequate resources to improve patient safety'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='3. Hospital management seems interested in patient safety only after an adverse event happens'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='4. When transferring patients, important information is often left out'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='5. During shift changes, important patient care information is often left out'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='6. During shift changes, there is adequate time to exchange all key patient care information'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g1',
            field=models.CharField(blank=True, choices=[('1', 'Less than 1 year'), ('2', '1 to 5 years'), ('3', '6 to 10 years'), ('4', '11 or more years')], max_length=1, null=True, verbose_name='1. How long have you worked in this hospital?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g2',
            field=models.CharField(blank=True, choices=[('1', 'Less than 1 year'), ('2', '1 to 5 years'), ('3', '6 to 10 years'), ('4', '11 or more years')], max_length=1, null=True, verbose_name='2. How long have you worked in your current unit/work area?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g3',
            field=models.CharField(blank=True, choices=[('1', 'Less than 30 hours/week'), ('2', '30 to 40 hours/week'), ('3', 'More than 40 hours/week')], max_length=1, null=True, verbose_name='3. Typically, how many hours per week do you work in this hospital?'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g4',
            field=models.CharField(blank=True, choices=[('1', 'YES'), ('2', 'NO')], max_length=1, null=True, verbose_name='4. Do you typically have direct interaction or contact with patients?'),
        ),
        migrations.AlterField(
            model_name='patientsafetyheader',
            name='key_intervention_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetyheader',
            name='surveymonth',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patientsafetyheader',
            name='surveyyear',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=4),
        ),
        migrations.AlterField(
            model_name='workarea',
            name='work_area_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
