# Generated by Django 5.1.4 on 2025-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_patientsafetyheader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='a9',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='b1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='b2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='b3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='c7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='d1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='d2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Most of the time'), (5, 'Always'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='d3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'None'), (2, '1 to 2'), (3, '3 to 5'), (4, '6 to 10'), (5, '11 or more')], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='e1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='f6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neither Agree nor Disagree'), (4, 'Agree'), (5, 'Strongly Agree'), (9, "Does Not Apply / Don't Know")], null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g1',
            field=models.CharField(blank=True, choices=[('1', 'Less than 1 year'), ('2', '1 to 5 years'), ('3', '6 to 10 years'), ('4', '11 or more years')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g2',
            field=models.CharField(blank=True, choices=[('1', 'Less than 1 year'), ('2', '1 to 5 years'), ('3', '6 to 10 years'), ('4', '11 or more years')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g3',
            field=models.CharField(blank=True, choices=[('1', 'Less than 30 hours per week'), ('2', '30 to 40 hours per week'), ('3', 'More than 40 hours per week')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='g4',
            field=models.CharField(blank=True, choices=[('1', 'YES, I typically have direct interaction or contact with patients'), ('2', 'NO, I typically do NOT have direct interaction or contact with patients')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workarea',
            name='work_area_name',
            field=models.CharField(max_length=150),
        ),
    ]
