# Generated by Django 5.1.4 on 2026-01-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_patientsafetyheader_approval_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsafetyheader',
            name='staff_profession',
        ),
    ]
