# Generated by Django 5.1.4 on 2026-01-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        ('survey', '0006_remove_patientsafetyheader_staff_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsafetyheader',
            name='staff_profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_safety_headers', to='mentorship.position'),
        ),
    ]
