# Generated by Django 5.1.4 on 2026-01-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0097_position'),
        ('survey', '0007_patientsafetyheader_staff_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsafetyheader',
            name='staff_profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_safety_headers', to='hiva.position'),
        ),
    ]
