# Generated by Django 5.1.4 on 2026-01-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_patientsafetyheader_staff_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h10_informed_consent',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Some of the time'), (4, 'Most of the time'), (5, 'Every time'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Informed consent obtained prior to procedures/exams during labor & delivery'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h11_companionship_choice',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Some of the time'), (4, 'Most of the time'), (5, 'Every time'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Women allowed choice of companionship during labor & delivery'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h12_treated_respectfully',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Some of the time'), (4, 'Most of the time'), (5, 'Every time'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Women treated with respect and in a friendly manner during labor & delivery'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h1_wrong_medication',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Wrong medication (in the past 12 months, frequency witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h2_wrong_dose',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Wrong dose of medication (in the past 12 months, frequency witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h3_wrong_route',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Wrong route of medication (in the past 12 months, frequency witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h4_wrong_surgical_procedure',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Wrong surgical procedure (in the past 12 months, frequency witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h5_physical_abuse_ld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Physical abuse during labor and delivery (violations witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h6_verbal_abuse_ld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Verbal abuse during labor and delivery (violations witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h7_stigma_discrimination',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Stigma or discrimination (violations witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h8_privacy_confidentiality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='Violations of privacy or confidentiality (violations witnessed)'),
        ),
        migrations.AddField(
            model_name='patientsafetydetails',
            name='h9_no_staff_at_birth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='No staff member present at the time of birth (violations witnessed)'),
        ),
    ]
