# Generated by Django 5.1.4 on 2026-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_patientsafetydetails_h10_informed_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h10_informed_consent',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Some of the time'), (4, 'Most of the time'), (5, 'Every time'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H10. Informed consent obtained prior to procedures/exams (labor & delivery)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h11_companionship_choice',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Some of the time'), (4, 'Most of the time'), (5, 'Every time'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H11. Women allowed choice of companionship during labor & delivery'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h12_treated_respectfully',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Some of the time'), (4, 'Most of the time'), (5, 'Every time'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H12. Women treated with respect and in a friendly manner during labor & delivery'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h1_wrong_medication',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H1. Wrong medication (past 12 months - frequency witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h2_wrong_dose',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H2. Wrong dose of medication (past 12 months - frequency witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h3_wrong_route',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H3. Wrong route of medication (past 12 months - frequency witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h4_wrong_surgical_procedure',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H4. Wrong surgical procedure (past 12 months - frequency witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h5_physical_abuse_ld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H5. Physical abuse during labor & delivery (violations witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h6_verbal_abuse_ld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H6. Verbal abuse during labor & delivery (violations witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h7_stigma_discrimination',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H7. Stigma or discrimination (violations witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h8_privacy_confidentiality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H8. Violations of privacy or confidentiality (violations witnessed)'),
        ),
        migrations.AlterField(
            model_name='patientsafetydetails',
            name='h9_no_staff_at_birth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Never'), (2, 'Once or twice per year'), (3, 'Once every three months'), (4, 'Once every month'), (5, 'At least every 1-2 weeks'), (9, "Does Not Apply / Don't Know")], null=True, verbose_name='H9. No staff member present at the time of birth (violations witnessed)'),
        ),
    ]
