# Generated by Django 5.1.4 on 2026-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_patientsafetydetails_a1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsafetyheader',
            name='key_intervention_name',
            field=models.CharField(choices=[('AIM', 'AIM'), ('SAFE_SURGERY', 'SAFE_SURGERY')], default='AIM', max_length=255),
        ),
    ]
