# Generated by Django 5.1.4 on 2026-01-04 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiva', '0086_remove_hqipassessment_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KMDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('brief', 'Learning Brief'), ('sop', 'SOP / Guideline'), ('case', 'Case Study'), ('aar', 'After Action Review'), ('report', 'Report'), ('training', 'Training Material')], max_length=20)),
                ('theme', models.CharField(choices=[('ANC', 'ANC'), ('PNC', 'PNC'), ('L&D', 'Labour & Delivery'), ('PPH', 'PPH'), ('PEE', 'PE/E'), ('MNM', 'Maternal Near Miss'), ('NBCC', 'NBCC / Newborn'), ('QoC', 'Quality of Care'), ('Other', 'Other')], default='QoC', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='km_docs/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='km_docs_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.district')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.facility')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.province')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KMRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('ANC', 'ANC'), ('PNC', 'PNC'), ('L&D', 'Labour & Delivery'), ('PPH', 'PPH'), ('PEE', 'PE/E'), ('MNM', 'Maternal Near Miss'), ('NBCC', 'NBCC / Newborn'), ('QoC', 'Quality of Care'), ('Other', 'Other')], default='QoC', max_length=20)),
                ('recommendation', models.TextField()),
                ('responsible_person', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('implemented_on', models.DateField(blank=True, null=True)),
                ('evidence_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='km_recs_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.district')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiva.facility')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiva.province')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='km_dashboard.kmdocument')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
    ]
