# Generated by Django 5.1.4 on 2026-01-05 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0086_remove_hqipassessment_remarks_and_more'),
        ('km_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kmdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kmdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='km_docs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='km_docs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='doc_type',
            field=models.CharField(choices=[('brief', 'Learning Brief'), ('sop', 'SOP / Guideline'), ('case', 'Case Study'), ('aar', 'After Action Review'), ('report', 'Report'), ('training', 'Training Material')], max_length=20, verbose_name='Type of document'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.facility', verbose_name='Health Facility'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='km_docs/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='month',
            field=models.PositiveIntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='theme',
            field=models.CharField(choices=[('ANC', 'ANC'), ('PNC', 'PNC'), ('L&D', 'Labour & Delivery'), ('PPH', 'PPH'), ('PEE', 'PE/E'), ('MNM', 'Maternal Near Miss'), ('NBCC', 'NBCC / Newborn'), ('QoC', 'Quality of Care'), ('Other', 'Other')], default='ANC', max_length=20, verbose_name='Technical Area'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name of the knowledge product'),
        ),
        migrations.AlterField(
            model_name='kmdocument',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='km_recs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hiva.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='evidence_notes',
            field=models.TextField(blank=True, default='', verbose_name='Evidence that Action Happened'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiva.facility', verbose_name='Health Facility'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='implemented_on',
            field=models.DateField(blank=True, null=True, verbose_name='Date Completed'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='month',
            field=models.PositiveIntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hiva.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='recommendation',
            field=models.TextField(verbose_name='Recommandation'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Responsible Person'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='km_dashboard.kmdocument', verbose_name='Source Document'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=20, verbose_name='Action Progress'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='theme',
            field=models.CharField(choices=[('ANC', 'ANC'), ('PNC', 'PNC'), ('L&D', 'Labour & Delivery'), ('PPH', 'PPH'), ('PEE', 'PE/E'), ('MNM', 'Maternal Near Miss'), ('NBCC', 'NBCC / Newborn'), ('QoC', 'Quality of Care'), ('Other', 'Other')], default='ANC', max_length=20, verbose_name='Technical Area of Recommendation'),
        ),
        migrations.AlterField(
            model_name='kmrecommendation',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
