# Generated by Django 5.1.4 on 2026-01-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('km_dashboard', '0003_kmrecommendation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmdocument',
            options={'ordering': ['-year', '-month', '-created_at'], 'verbose_name': 'Knowledge MGT Documents', 'verbose_name_plural': 'Knowledge MGT Documents'},
        ),
        migrations.AlterModelOptions(
            name='kmrecommendation',
            options={'ordering': ['-year', '-month', '-created_at'], 'verbose_name': 'Knowledge MGT Recommandations', 'verbose_name_plural': 'Knowledge MGT Recommandations'},
        ),
    ]
