# Generated by Django 5.1.4 on 2026-04-26 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQMUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('round_name', models.CharField(max_length=50)),
                ('excel_file', models.FileField(upload_to='qqm/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QQMFacilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hfcode', models.IntegerField(db_index=True)),
                ('hfname_excel', models.CharField(blank=True, max_length=255, null=True)),
                ('structural_score', models.FloatField(blank=True, null=True)),
                ('outcome_score', models.FloatField(blank=True, null=True)),
                ('content_score', models.FloatField(blank=True, null=True)),
                ('qqm_score', models.FloatField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiva.facility')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqm.qqmupload')),
            ],
            options={
                'unique_together': {('upload', 'hfcode')},
            },
        ),
        migrations.CreateModel(
            name='QQMRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structural_data', models.JSONField(blank=True, null=True)),
                ('outcome_data', models.JSONField(blank=True, null=True)),
                ('content_data', models.JSONField(blank=True, null=True)),
                ('workforce_data', models.JSONField(blank=True, null=True)),
                ('mss_data', models.JSONField(blank=True, null=True)),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qqm.qqmfacilityscore')),
            ],
        ),
    ]
