# Generated by Django 5.1.4 on 2026-04-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiva', '0120_alter_qicdataset_options'),
        ('qqm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qqmfacilityscore',
            options={'ordering': ['upload', 'hfcode']},
        ),
        migrations.AlterModelOptions(
            name='qqmupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='qqmrawdata',
            old_name='content_data',
            new_name='exit_vignette_data',
        ),
        migrations.RemoveField(
            model_name='qqmrawdata',
            name='outcome_data',
        ),
        migrations.AddField(
            model_name='qqmupload',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qqmupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='qqmupload',
            name='total_imported',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qqmupload',
            name='total_matched_facilities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qqmupload',
            name='total_unmatched_facilities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qqmfacilityscore',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qqm_scores', to='hiva.facility'),
        ),
        migrations.AlterField(
            model_name='qqmfacilityscore',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_scores', to='qqm.qqmupload'),
        ),
        migrations.AlterField(
            model_name='qqmrawdata',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='qqm.qqmfacilityscore'),
        ),
        migrations.AlterField(
            model_name='qqmupload',
            name='excel_file',
            field=models.FileField(upload_to='qqm_uploads/'),
        ),
        migrations.AlterField(
            model_name='qqmupload',
            name='round_name',
            field=models.CharField(help_text='Example: R1, R2, R3, R4', max_length=50),
        ),
    ]
