# Generated by Django 5.1.4 on 2026-04-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqm', '0002_alter_qqmfacilityscore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQMStructuralDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1_general_management', models.FloatField(blank=True, null=True)),
                ('d2_hygiene', models.FloatField(blank=True, null=True)),
                ('d3_opd', models.FloatField(blank=True, null=True)),
                ('d4_fp', models.FloatField(blank=True, null=True)),
                ('d5_lab', models.FloatField(blank=True, null=True)),
                ('d6_drugs', models.FloatField(blank=True, null=True)),
                ('d7_tracer', models.FloatField(blank=True, null=True)),
                ('d8_maternity', models.FloatField(blank=True, null=True)),
                ('d9_epi', models.FloatField(blank=True, null=True)),
                ('d10_anc', models.FloatField(blank=True, null=True)),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qqm.qqmfacilityscore')),
            ],
        ),
    ]
